<template>
  <div class="app-container">
    <el-alert title="候选声音不会出现在开发者目录；发布后才可被 Application 使用。" type="info" :closable="false" class="mb16" />
    <el-card :header="editingVoiceId ? '保存新的声音版本' : '保存官方声音候选'" class="mb16">
      <el-form label-width="100px" inline>
        <el-form-item label="名称" required><el-input v-model="form.name" maxlength="100" /></el-form-item>
        <el-form-item label="官方服务" required><el-select v-model="form.officialServiceId" @change="selectService"><el-option v-for="item in services" :key="item.serviceId" :label="`${item.name}（${item.modelId}）`" :value="item.serviceId" /></el-select></el-form-item>
        <el-form-item label="音色" required><el-select v-model="form.voiceAlias"><el-option v-for="item in selectedService?.capability.voices || []" :key="item.id" :label="item.displayName" :value="item.id" /></el-select></el-form-item>
        <el-form-item label="语言"><el-select v-model="form.language"><el-option v-for="language in selectedService?.capability.languages || []" :key="language" :value="language" :label="language" /></el-select></el-form-item>
        <el-form-item v-for="(range, name) in selectedService?.capability.parameters || {}" :key="name" :label="String(name)"><el-input-number v-model="form.parameters[name]" :min="range.minimum" :max="range.maximum" :step="0.1" /></el-form-item>
        <template v-if="selectedService?.capability.referenceVoice"><el-form-item label="参考音频"><el-select v-model="form.referenceAssetId" clearable><el-option v-for="item in references" :key="item.id" :value="item.id" :label="item.name" /></el-select><input type="file" accept="audio/wav" @change="uploadReference" /></el-form-item><el-form-item label="参考文本"><el-input v-model="form.referenceText" maxlength="2000" /></el-form-item></template>
        <el-form-item label="备用声音"><el-select v-model="form.fallbackVoiceVersionId" clearable placeholder="不使用备用"><el-option v-for="item in publishedVoices" :key="item.voiceId" :value="item.currentVersionId!" :label="item.name" /></el-select></el-form-item>
        <el-form-item v-if="form.fallbackVoiceVersionId"><el-checkbox v-model="form.allowVoiceChange">允许故障时改变音色（保存时校验兼容性）</el-checkbox></el-form-item>
        <el-form-item label="说明"><el-input v-model="form.description" maxlength="1000" /></el-form-item>
        <el-form-item><el-button type="primary" @click="saveCandidate">{{ editingVoiceId ? '保存新版本' : '保存候选' }}</el-button><el-button v-if="editingVoiceId" @click="editingVoiceId = ''">取消编辑</el-button></el-form-item>
      </el-form>
    </el-card>
    <el-card class="mb16" header="执行服务与任务"><el-button @click="refreshDiagnostics">刷新状态与任务</el-button><span v-if="readiness"> API：{{ readiness.apiReachable ? '可达' : '不可达' }} · 模型：{{ readiness.modelReady ? '就绪' : '未就绪' }}（不代表合成成功）</span><el-table :data="readiness?.services || []"><el-table-column prop="name" label="服务" /><el-table-column prop="providerType" label="执行类型" /><el-table-column label="配置"><template #default="{ row }">{{ row.configValid ? "合法" : "无效" }}</template></el-table-column><el-table-column label="API"><template #default="{ row }">{{ row.apiReachable ? "可达" : "不可达" }}</template></el-table-column><el-table-column label="执行模型"><template #default="{ row }">{{ row.modelReady ? "就绪" : "未就绪" }}</template></el-table-column><el-table-column prop="lastSynthesisStatus" label="最近合成" /></el-table><el-table :data="tasks"><el-table-column prop="taskId" label="任务" /><el-table-column prop="purpose" label="用途" /><el-table-column prop="status" label="状态" /><el-table-column prop="errorCode" label="原因" /><el-table-column prop="settlement" label="积分收尾" /><el-table-column label="降级"><template #default="{ row }">{{ row.degraded ? '已改变音色' : '否' }}</template></el-table-column><el-table-column label="事实投递"><template #default="{ row }">{{ row.factDeliveryReview ? "需核对" : "正常或投递中" }}</template></el-table-column><el-table-column label="执行尝试"><template #default="{ row }"><div v-for="attempt in row.attempts" :key="attempt.attemptId">{{ attempt.providerType }} · {{ attempt.state }} · {{ attempt.costSource }} · {{ attempt.reasonCode }} {{ row.winnerAttemptId === attempt.attemptId ? '已采用' : '' }}</div></template></el-table-column></el-table></el-card>
    <el-table :data="voices" v-loading="loading" border>
      <el-table-column prop="name" label="名称" min-width="160" />
      <el-table-column prop="status" label="状态" width="110"><template #default="{ row }"><el-tag :type="row.status === 'PUBLISHED' ? 'success' : 'warning'">{{ row.status }}</el-tag></template></el-table-column>
      <el-table-column prop="voiceAlias" label="当前音色" width="130" />
      <el-table-column label="操作" min-width="220"><template #default="{ row }"><el-button link type="primary" @click="openDetail(row)">版本与发布</el-button></template></el-table-column>
    </el-table>
    <el-dialog v-model="detailOpen" :title="detail?.name || '官方声音'" width="720px">
      <el-alert title="试听只执行当前候选，不使用备用；云服务可能收费，测试音与自部署服务不代表免费平台业务播报。" type="warning" :closable="false" /><el-button :disabled="auditionBusy" @click="newAudition">开始新的试听请求</el-button><el-input v-model="auditionText" maxlength="200" class="mt16" /><audio v-if="auditionUrl" :src="auditionUrl" controls class="mt16" @ended="auditionComplete = true" />
      <el-table :data="detail?.versions || []" border><el-table-column prop="versionNo" label="版本" width="80" /><el-table-column prop="voiceAlias" label="音色" /><el-table-column prop="providerType" label="执行类型" /><el-table-column label="主备与参考"><template #default="{ row }"><div>{{ row.fallbackVoiceVersionId ? '备用版本：'+row.fallbackVoiceVersionId : '无备用' }} {{ row.allowVoiceChange ? '允许音色变化' : '' }}</div><div v-if="row.referenceAssetId">参考音频：{{ referenceName(row.referenceAssetId) }}</div></template></el-table-column><el-table-column label="操作" width="220"><template #default="{ row }"><el-button link @click="editVersion(row)">编辑为新版本</el-button><el-button link type="primary" :loading="auditionBusy" @click="audition(row.versionId)">试听</el-button><el-button link type="success" :disabled="detail?.currentVersionId === row.versionId || auditionVersion !== row.versionId || !auditionComplete" @click="publish(row)">发布</el-button></template></el-table-column></el-table>
    </el-dialog>
  </div>
</template>
<script setup lang="ts" name="OfficialVoices">
import { voiceReadiness, voiceTasks, voiceReferences, uploadVoiceReference, type VoiceTask, type OfficialVoiceVersion, createOfficialVoiceVersion, auditionOfficialVoice, createOfficialVoice, getOfficialVoice, listOfficialVoiceServices, listOfficialVoices, publishOfficialVoice, type OfficialVoice, type OfficialVoiceService, type OfficialVoiceSummary } from '@/api/asset/official-voice'
const { proxy } = getCurrentInstance()
const loading = ref(false); const services = ref<OfficialVoiceService[]>([]); const voices = ref<OfficialVoiceSummary[]>([]); const detail = ref<OfficialVoice>(); const detailOpen = ref(false)
const editingVoiceId = ref(''); const editingRevision = ref('');
const auditionKey = ref(crypto.randomUUID()); const auditionRequest = ref('');
const tasks = ref<VoiceTask[]>([]); const references = ref<{ id: string; name: string }[]>([]); const readiness = ref<import('@/api/asset/official-voice').VoiceReadiness>();
function refreshDiagnostics() { voiceReadiness().then(r => readiness.value = r.data); voiceTasks().then(r => tasks.value = r.data || []) }
async function uploadReference(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; const result = await uploadVoiceReference(file); references.value = (await voiceReferences()).data || []; form.referenceAssetId = result.data?.referenceAssetId || '' }
const auditionText = ref('你好，这是官方声音试听。'); const auditionUrl = ref(''); const auditionVersion = ref(''); const auditionComplete = ref(false); const auditionBusy = ref(false)
function clearAudition() { if (auditionUrl.value) URL.revokeObjectURL(auditionUrl.value); auditionUrl.value = ''; auditionVersion.value = ''; auditionComplete.value = false }
function audition(versionId: string) { if (!detail.value || auditionBusy.value) return; proxy?.$modal.confirm('试听可能产生云服务费用；相同请求重读不会重新合成。确认继续？').then(async () => { clearAudition(); auditionBusy.value = true; try { const request = `${versionId}:${auditionText.value}`; if (auditionRequest.value !== request) { auditionKey.value = crypto.randomUUID(); auditionRequest.value = request }; const blob = await auditionOfficialVoice(detail.value!.voiceId, versionId, auditionText.value, auditionKey.value); auditionUrl.value = URL.createObjectURL(blob); auditionVersion.value = versionId } finally { auditionBusy.value = false } }) }
function newAudition() { clearAudition(); auditionRequest.value = ''; auditionKey.value = crypto.randomUUID(); proxy?.$modal.msgSuccess('下次试听将创建新请求，可能产生新费用。') }
onBeforeUnmount(clearAudition)
const form = reactive({ name: '', description: '', officialServiceId: '', voiceAlias: '', language: 'zh-CN', parameters: {} as Record<string, number>, fallbackVoiceVersionId: '', allowVoiceChange: false, referenceAssetId: '', referenceText: '' })
const selectedService = computed(() => services.value.find((item: OfficialVoiceService) => item.serviceId === form.officialServiceId))
const publishedVoices = computed(() => voices.value.filter((v: OfficialVoiceSummary) => v.status === 'PUBLISHED' && v.currentVersionId))
function selectService() { form.voiceAlias = selectedService.value?.availableVoiceAliases[0] || ''; form.language = selectedService.value?.capability.languages[0] || 'zh-CN'; const ranges: Record<string, { defaultValue: number }> = selectedService.value?.capability.parameters || {}; form.parameters = Object.fromEntries(Object.entries(ranges).map(([name, range]) => [name, range.defaultValue])); form.referenceAssetId = ''; form.referenceText = '' }
function reload() { loading.value = true; Promise.all([listOfficialVoiceServices(), listOfficialVoices()]).then(([service, voice]) => { services.value = service.data || []; voices.value = voice.data?.items || []; if (!form.officialServiceId && services.value[0]) { form.officialServiceId = services.value[0].serviceId; selectService() } }).finally(() => { loading.value = false }) }
function input() { if (!selectedService.value || !form.name.trim() || (!form.voiceAlias && !form.referenceAssetId)) return undefined; return { name: form.name.trim(), description: form.description.trim() || undefined, officialServiceId: form.officialServiceId, expectedServiceRevision: selectedService.value.revision, voiceAlias: form.voiceAlias || `reference:${form.referenceAssetId}`, language: form.language, parameters: form.parameters, fallbackVoiceVersionId: form.fallbackVoiceVersionId || undefined, allowVoiceChange: form.allowVoiceChange, referenceAssetId: form.referenceAssetId || undefined, referenceText: form.referenceText || undefined } }
function saveCandidate() { const data = input(); if (!data) return proxy?.$modal.msgWarning('请填写名称并选择已启用的官方服务和音色。'); (editingVoiceId.value ? createOfficialVoiceVersion(editingVoiceId.value, editingRevision.value, data) : createOfficialVoice(data)).then(() => { proxy?.$modal.msgSuccess('候选声音已保存，尚未公开。'); form.name = ''; form.description = ''; editingVoiceId.value = ''; reload() }) }
function referenceName(id: string) { return references.value.find((item: { id: string; name: string }) => item.id === id)?.name || id }
function editVersion(version: OfficialVoiceVersion) { if (!detail.value) return; if (!services.value.some((service: OfficialVoiceService) => service.serviceId === version.officialServiceId)) return proxy?.$modal.msgWarning('原服务不可用，请先启用或登记合适的服务。'); editingVoiceId.value = detail.value.voiceId; editingRevision.value = detail.value.revision; Object.assign(form, { name: detail.value.name, description: detail.value.description || '', officialServiceId: version.officialServiceId, voiceAlias: version.referenceAssetId ? '' : version.voiceAlias, language: version.language || 'zh-CN', parameters: { ...version.parameters }, referenceAssetId: version.referenceAssetId || '', referenceText: version.referenceText || '', fallbackVoiceVersionId: version.fallbackVoiceVersionId || '', allowVoiceChange: version.allowVoiceChange || false }); detailOpen.value = false }
function openDetail(row: OfficialVoiceSummary) { clearAudition(); getOfficialVoice(row.voiceId).then((response: { data?: OfficialVoice }) => { detail.value = response.data; detailOpen.value = true }) }
function publish(version: { versionId: string }) { if (!detail.value) return; proxy?.$modal.confirm('确认发布该官方声音版本？新 Session 才会使用新的当前版本。').then(() => publishOfficialVoice(detail.value!.voiceId, version.versionId, detail.value!.revision)).then(() => { proxy?.$modal.msgSuccess('官方声音已发布。'); detailOpen.value = false; reload() }) }
onMounted(() => { reload(); voiceReferences().then(r => references.value = r.data || []) })
</script>
<style scoped>.mb16 { margin-bottom: 16px; }.mt16 { margin-top: 16px; }</style>
