
-- 16 curated RuoYi core/compatibility tables; no upstream sample records.
-- sys_user and platform unique keys include database design §4.2 overrides.
CREATE TABLE IF NOT EXISTS `sys_dept` (
  `dept_id`           bigint(20)      not null auto_increment    comment '部门id',
  `parent_id`         bigint(20)      default 0                  comment '父部门id',
  `ancestors`         varchar(50)     default ''                 comment '祖级列表',
  `dept_name`         varchar(30)     default ''                 comment '部门名称',
  `order_num`         int(4)          default 0                  comment '显示顺序',
  `leader`            varchar(20)     default null               comment '负责人',
  `phone`             varchar(11)     default null               comment '联系电话',
  `email`             varchar(50)     default null               comment '邮箱',
  `status`            char(1)         default '0'                comment '部门状态（0正常 1停用）',
  `del_flag`          char(1)         default '0'                comment '删除标志（0代表存在 2代表删除）',
  `create_by`         varchar(64)     default ''                 comment '创建者',
  `create_time` 	    datetime                                   comment '创建时间',
  `update_by`         varchar(64)     default ''                 comment '更新者',
  `update_time`       datetime                                   comment '更新时间',
  primary key (dept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci auto_increment=200 comment = '部门表';
CREATE TABLE IF NOT EXISTS `sys_user` (
  `user_id`           bigint(20)      not null auto_increment    comment '用户ID',
  `dept_id`           bigint(20)      default null               comment '部门ID',
  `user_name`         varchar(30)     not null                   comment '用户账号',
  `nick_name`         varchar(30)     not null                   comment '用户昵称',
  `user_type`         varchar(2)      default '00'               comment '用户类型（00系统用户）',
  `email`             varchar(254)    not null                   comment '注册邮箱原展示值',
  `email_normalized`  varchar(254)    not null                   comment '平台规范化注册邮箱',
  `email_verified_at` datetime(3)                                comment '邮箱验证完成时间，UTC',
  `auth_epoch`        bigint          not null default 1         comment '账号持久撤销版本',
  `avatar_file_id`    bigint                                     comment '账号头像p_file逻辑引用',
  `phonenumber`       varchar(11)     default ''                 comment '手机号码',
  `sex`               char(1)         default '0'                comment '用户性别（0男 1女 2未知）',
  `avatar`            varchar(100)    default ''                 comment '头像地址',
  `password`          varchar(100)    not null                   comment '若依格式密码哈希',
  `status`            char(1)         default '0'                comment '账号状态（0正常 1停用）',
  `del_flag`          char(1)         default '0'                comment '删除标志（0代表存在 2代表删除）',
  `login_ip`          varchar(128)    default ''                 comment '最后登录IP',
  `login_date`        datetime                                   comment '最后登录时间',
  `pwd_update_date`   datetime                                   comment '密码最后更新时间',
  `create_by`         varchar(64)     default ''                 comment '创建者',
  `create_time`       datetime                                   comment '创建时间',
  `update_by`         varchar(64)     default ''                 comment '更新者',
  `update_time`       datetime                                   comment '更新时间',
  `remark`            varchar(500)    default null               comment '备注',
  primary key (user_id),
  UNIQUE KEY `uq_sys_user_user_name` (`user_name`),
  UNIQUE KEY `uq_sys_user_email_normalized` (`email_normalized`),
  CONSTRAINT `ck_sys_user_auth_epoch` CHECK (`auth_epoch` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci auto_increment=100 comment = '用户信息表';
CREATE TABLE IF NOT EXISTS `sys_post` (
  `post_id`       bigint(20)      not null auto_increment    comment '岗位ID',
  `post_code`     varchar(64)     not null                   comment '岗位编码',
  `post_name`     varchar(50)     not null                   comment '岗位名称',
  `post_sort`     int(4)          not null                   comment '显示顺序',
  `status`        char(1)         not null                   comment '状态（0正常 1停用）',
  `create_by`     varchar(64)     default ''                 comment '创建者',
  `create_time`   datetime                                   comment '创建时间',
  `update_by`     varchar(64)     default ''			       comment '更新者',
  `update_time`   datetime                                   comment '更新时间',
  `remark`        varchar(500)    default null               comment '备注',
  primary key (post_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci comment = '岗位信息表';
CREATE TABLE IF NOT EXISTS `sys_role` (
  `role_id`              bigint(20)      not null auto_increment    comment '角色ID',
  `role_name`            varchar(30)     not null                   comment '角色名称',
  `role_key`             varchar(100)    not null                   comment '角色权限字符串',
  `role_sort`            int(4)          not null                   comment '显示顺序',
  `data_scope`           char(1)         default '1'                comment '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）',
  `menu_check_strictly`  tinyint(1)      default 1                  comment '菜单树选择项是否关联显示',
  `dept_check_strictly`  tinyint(1)      default 1                  comment '部门树选择项是否关联显示',
  `status`               char(1)         not null                   comment '角色状态（0正常 1停用）',
  `del_flag`             char(1)         default '0'                comment '删除标志（0代表存在 2代表删除）',
  `create_by`            varchar(64)     default ''                 comment '创建者',
  `create_time`          datetime                                   comment '创建时间',
  `update_by`            varchar(64)     default ''                 comment '更新者',
  `update_time`          datetime                                   comment '更新时间',
  `remark`               varchar(500)    default null               comment '备注',
  primary key (role_id),
  UNIQUE KEY `uq_sys_role_role_key` (`role_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci auto_increment=100 comment = '角色信息表';
CREATE TABLE IF NOT EXISTS `sys_menu` (
  `menu_id`           bigint(20)      not null auto_increment    comment '菜单ID',
  `menu_name`         varchar(50)     not null                   comment '菜单名称',
  `parent_id`         bigint(20)      default 0                  comment '父菜单ID',
  `order_num`         int(4)          default 0                  comment '显示顺序',
  `path`              varchar(200)    default ''                 comment '路由地址',
  `component`         varchar(255)    default null               comment '组件路径',
  `query`             varchar(255)    default null               comment '路由参数',
  `route_name`        varchar(50)     default ''                 comment '路由名称',
  `is_frame`          int(1)          default 1                  comment '是否为外链（0是 1否）',
  `is_cache`          int(1)          default 0                  comment '是否缓存（0缓存 1不缓存）',
  `menu_type`         char(1)         default ''                 comment '菜单类型（M目录 C菜单 F按钮）',
  `visible`           char(1)         default 0                  comment '菜单状态（0显示 1隐藏）',
  `status`            char(1)         default 0                  comment '菜单状态（0正常 1停用）',
  `perms`             varchar(100)    default null               comment '权限标识',
  `icon`              varchar(100)    default '#'                comment '菜单图标',
  `create_by`         varchar(64)     default ''                 comment '创建者',
  `create_time`       datetime                                   comment '创建时间',
  `update_by`         varchar(64)     default ''                 comment '更新者',
  `update_time`       datetime                                   comment '更新时间',
  `remark`            varchar(500)    default ''                 comment '备注',
  primary key (menu_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci auto_increment=2000 comment = '菜单权限表';
CREATE TABLE IF NOT EXISTS `sys_user_role` (
  `user_id`   bigint(20) not null comment '用户ID',
  `role_id`   bigint(20) not null comment '角色ID',
  primary key(user_id, role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci comment = '用户和角色关联表';
CREATE TABLE IF NOT EXISTS `sys_role_menu` (
  `role_id`   bigint(20) not null comment '角色ID',
  `menu_id`   bigint(20) not null comment '菜单ID',
  primary key(role_id, menu_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci comment = '角色和菜单关联表';
CREATE TABLE IF NOT EXISTS `sys_role_dept` (
  `role_id`   bigint(20) not null comment '角色ID',
  `dept_id`   bigint(20) not null comment '部门ID',
  primary key(role_id, dept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci comment = '角色和部门关联表';
CREATE TABLE IF NOT EXISTS `sys_user_post` (
  `user_id`   bigint(20) not null comment '用户ID',
  `post_id`   bigint(20) not null comment '岗位ID',
  primary key (user_id, post_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci comment = '用户与岗位关联表';
CREATE TABLE IF NOT EXISTS `sys_oper_log` (
  `oper_id`           bigint(20)      not null auto_increment    comment '日志主键',
  `title`             varchar(50)     default ''                 comment '模块标题',
  `business_type`     int(2)          default 0                  comment '业务类型（0其它 1新增 2修改 3删除）',
  `method`            varchar(200)    default ''                 comment '方法名称',
  `request_method`    varchar(10)     default ''                 comment '请求方式',
  `operator_type`     int(1)          default 0                  comment '操作类别（0其它 1后台用户 2手机端用户）',
  `oper_name`         varchar(50)     default ''                 comment '操作人员',
  `dept_name`         varchar(50)     default ''                 comment '部门名称',
  `oper_url`          varchar(255)    default ''                 comment '请求URL',
  `oper_ip`           varchar(128)    default ''                 comment '主机地址',
  `oper_location`     varchar(255)    default ''                 comment '操作地点',
  `oper_param`        varchar(2000)   default ''                 comment '请求参数',
  `json_result`       varchar(2000)   default ''                 comment '返回参数',
  `status`            int(1)          default 0                  comment '操作状态（0正常 1异常）',
  `error_msg`         varchar(2000)   default ''                 comment '错误消息',
  `oper_time`         datetime                                   comment '操作时间',
  `cost_time`         bigint(20)      default 0                  comment '消耗时间',
  primary key (oper_id),
  key idx_sys_oper_log_bt (business_type),
  key idx_sys_oper_log_s  (status),
  key idx_sys_oper_log_ot (oper_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci auto_increment=100 comment = '操作日志记录';
CREATE TABLE IF NOT EXISTS `sys_dict_type` (
  `dict_id`          bigint(20)      not null auto_increment    comment '字典主键',
  `dict_name`        varchar(100)    default ''                 comment '字典名称',
  `dict_type`        varchar(100)    default ''                 comment '字典类型',
  `status`           char(1)         default '0'                comment '状态（0正常 1停用）',
  `create_by`        varchar(64)     default ''                 comment '创建者',
  `create_time`      datetime                                   comment '创建时间',
  `update_by`        varchar(64)     default ''                 comment '更新者',
  `update_time`      datetime                                   comment '更新时间',
  `remark`           varchar(500)    default null               comment '备注',
  primary key (dict_id),
  UNIQUE KEY `uq_sys_dict_type_dict_type` (`dict_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci auto_increment=100 comment = '字典类型表';
CREATE TABLE IF NOT EXISTS `sys_dict_data` (
  `dict_code`        bigint(20)      not null auto_increment    comment '字典编码',
  `dict_sort`        int(4)          default 0                  comment '字典排序',
  `dict_label`       varchar(100)    default ''                 comment '字典标签',
  `dict_value`       varchar(100)    default ''                 comment '字典键值',
  `dict_type`        varchar(100)    default ''                 comment '字典类型',
  `css_class`        varchar(100)    default null               comment '样式属性（其他样式扩展）',
  `list_class`       varchar(100)    default null               comment '表格回显样式',
  `is_default`       char(1)         default 'N'                comment '是否默认（Y是 N否）',
  `status`           char(1)         default '0'                comment '状态（0正常 1停用）',
  `create_by`        varchar(64)     default ''                 comment '创建者',
  `create_time`      datetime                                   comment '创建时间',
  `update_by`        varchar(64)     default ''                 comment '更新者',
  `update_time`      datetime                                   comment '更新时间',
  `remark`           varchar(500)    default null               comment '备注',
  primary key (dict_code),
  UNIQUE KEY `uq_sys_dict_data_type_value` (`dict_type`, `dict_value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci auto_increment=100 comment = '字典数据表';
CREATE TABLE IF NOT EXISTS `sys_config` (
  `config_id`         int(5)          not null auto_increment    comment '参数主键',
  `config_name`       varchar(100)    default ''                 comment '参数名称',
  `config_key`        varchar(100)    default ''                 comment '参数键名',
  `config_value`      varchar(500)    default ''                 comment '参数键值',
  `config_type`       char(1)         default 'N'                comment '系统内置（Y是 N否）',
  `create_by`         varchar(64)     default ''                 comment '创建者',
  `create_time`       datetime                                   comment '创建时间',
  `update_by`         varchar(64)     default ''                 comment '更新者',
  `update_time`       datetime                                   comment '更新时间',
  `remark`            varchar(500)    default null               comment '备注',
  primary key (config_id),
  UNIQUE KEY `uq_sys_config_config_key` (`config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci auto_increment=100 comment = '参数配置表';
CREATE TABLE IF NOT EXISTS `sys_logininfor` (
  `info_id`        bigint(20)     not null auto_increment   comment '访问ID',
  `user_name`      varchar(50)    default ''                comment '用户账号',
  `ipaddr`         varchar(128)   default ''                comment '登录IP地址',
  `status`         char(1)        default '0'               comment '登录状态（0成功 1失败）',
  `msg`            varchar(255)   default ''                comment '提示信息',
  `access_time`    datetime                                 comment '访问时间',
  primary key (info_id),
  key idx_sys_logininfor_s  (status),
  key idx_sys_logininfor_lt (access_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci auto_increment=100 comment = '系统访问记录';
CREATE TABLE IF NOT EXISTS `sys_job` (
  `job_id`              bigint(20)    not null auto_increment    comment '任务ID',
  `job_name`            varchar(64)   default ''                 comment '任务名称',
  `job_group`           varchar(64)   default 'DEFAULT'          comment '任务组名',
  `invoke_target`       varchar(500)  not null                   comment '调用目标字符串',
  `cron_expression`     varchar(255)  default ''                 comment 'cron执行表达式',
  `misfire_policy`      varchar(20)   default '3'                comment '计划执行错误策略（1立即执行 2执行一次 3放弃执行）',
  `concurrent`          char(1)       default '1'                comment '是否并发执行（0允许 1禁止）',
  `status`              char(1)       default '0'                comment '状态（0正常 1暂停）',
  `create_by`           varchar(64)   default ''                 comment '创建者',
  `create_time`         datetime                                 comment '创建时间',
  `update_by`           varchar(64)   default ''                 comment '更新者',
  `update_time`         datetime                                 comment '更新时间',
  `remark`              varchar(500)  default ''                 comment '备注信息',
  primary key (job_id, job_name, job_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci auto_increment=100 comment = '定时任务调度表';
CREATE TABLE IF NOT EXISTS `sys_job_log` (
  `job_log_id`          bigint(20)     not null auto_increment    comment '任务日志ID',
  `job_name`            varchar(64)    not null                   comment '任务名称',
  `job_group`           varchar(64)    not null                   comment '任务组名',
  `invoke_target`       varchar(500)   not null                   comment '调用目标字符串',
  `job_message`         varchar(500)                              comment '日志信息',
  `status`              char(1)        default '0'                comment '执行状态（0正常 1失败）',
  `exception_info`      varchar(2000)  default ''                 comment '异常信息',
  `start_time`          datetime                                  comment '执行开始时间',
  `end_time`            datetime                                  comment '执行结束时间',
  `create_time`         datetime                                  comment '创建时间',
  primary key (job_log_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci comment = '定时任务调度日志表';

-- 35 platform business tables.
-- 账号与接入 / 邮箱验证与密码重置
CREATE TABLE IF NOT EXISTS `p_email_token` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `user_id` bigint NULL COMMENT '关联sys_user.user_id；注册前允许为空',
  `email` varchar(254) NOT NULL COMMENT '规范化邮箱',
  `purpose` varchar(24) NOT NULL COMMENT 'VERIFY_EMAIL/RESET_PASSWORD',
  `token_hash` binary(32) NOT NULL COMMENT '一次性随机令牌摘要，不存明文验证码',
  `expires_at` datetime(3) NOT NULL COMMENT '到期时间',
  `consumed_at` datetime(3) NULL COMMENT '成功消费时间',
  `failed_attempts` int NOT NULL DEFAULT 0 COMMENT '默认0；失败尝试次数',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_email_token_1` (`token_hash`),
  KEY `idx_p_email_token_1` (`email`, `purpose`, `created_at`),
  KEY `idx_p_email_token_2` (`expires_at`),
  CONSTRAINT `ck_p_email_token_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_email_token_user_id` CHECK (`user_id` > 0),
  CONSTRAINT `ck_p_email_token_purpose` CHECK (`purpose` IN ('VERIFY_EMAIL', 'RESET_PASSWORD')),
  CONSTRAINT `ck_p_email_token_failed_attempts` CHECK (`failed_attempts` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='邮箱验证与密码重置';

-- 账号与接入 / 管理Key与Application Secret
CREATE TABLE IF NOT EXISTS `p_access_key` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT 'sys_user.user_id',
  `application_id` bigint NULL COMMENT 'APPLICATION类型必填，MANAGEMENT类型为空',
  `key_type` varchar(24) NOT NULL COMMENT 'MANAGEMENT/APPLICATION',
  `name` varchar(100) COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '凭证显示名称',
  `public_id` varchar(48) NOT NULL COMMENT '对外可见且全局唯一的凭证标识',
  `secret_hash` binary(32) NOT NULL COMMENT '高熵Secret摘要或带服务端pepper的摘要',
  `hash_key_version` varchar(32) NOT NULL COMMENT '摘要方案/pepper版本',
  `display_suffix` varchar(8) NOT NULL COMMENT '脱敏显示后缀',
  `scopes` json NOT NULL COMMENT '本Key接入权限词表；APPLICATION存sessions:*，不存S运行权限',
  `status` varchar(20) NOT NULL COMMENT 'ACTIVE/DISABLED/DELETED',
  `expires_at` datetime(3) NULL COMMENT '可选有效期',
  `revoked_at` datetime(3) NULL COMMENT '撤销时间',
  `last_used_at` datetime(3) NULL COMMENT '最近使用，异步合并更新',
  `auth_epoch` bigint NOT NULL DEFAULT 1 COMMENT '默认1；轮换、停用、撤销递增，重新启用不复活旧授权',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_access_key_1` (`public_id`),
  KEY `idx_p_access_key_1` (`account_id`, `key_type`, `status`),
  KEY `idx_p_access_key_2` (`application_id`, `status`),
  CONSTRAINT `ck_p_access_key_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_access_key_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_access_key_application_id` CHECK (`application_id` > 0),
  CONSTRAINT `ck_p_access_key_key_type` CHECK (`key_type` IN ('MANAGEMENT', 'APPLICATION')),
  CONSTRAINT `ck_p_access_key_status` CHECK (`status` IN ('ACTIVE', 'DISABLED', 'DELETED')),
  CONSTRAINT `ck_p_access_key_auth_epoch` CHECK (`auth_epoch` > 0),
  CONSTRAINT `ck_p_access_key_application` CHECK ((`key_type` = 'MANAGEMENT' AND `application_id` IS NULL) OR (`key_type` = 'APPLICATION' AND `application_id` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='管理Key与Application Secret';

-- 账号与接入 / 平台需可解密的秘密
CREATE TABLE IF NOT EXISTS `p_secret` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '管理该秘密的账号；官方秘密由管理员账号管理',
  `purpose` varchar(24) NOT NULL COMMENT 'OFFICIAL_PROVIDER/RELAY_ACCESS/TOOL_ACCESS/WEBHOOK_SIGN',
  `name` varchar(100) COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '显示名称',
  `ciphertext` mediumblob NOT NULL COMMENT '经审核加密库输出的密文',
  `nonce` varbinary(32) NOT NULL COMMENT '随机nonce/IV',
  `auth_tag` varbinary(32) NOT NULL COMMENT 'AEAD认证标签',
  `key_version` varchar(32) NOT NULL COMMENT '部署主密钥版本',
  `algorithm` varchar(32) NOT NULL COMMENT '受支持算法标识',
  `display_suffix` varchar(8) NULL COMMENT '脱敏后缀',
  `status` varchar(20) NOT NULL COMMENT 'ACTIVE/DISABLED/DELETED',
  `revision` bigint NOT NULL DEFAULT 1 COMMENT '默认1；原子轮换序号',
  `expires_at` datetime(3) NULL COMMENT '有效期',
  PRIMARY KEY (`id`),
  KEY `idx_p_secret_1` (`account_id`, `purpose`, `status`),
  CONSTRAINT `ck_p_secret_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_secret_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_secret_purpose` CHECK (`purpose` IN ('OFFICIAL_PROVIDER', 'RELAY_ACCESS', 'TOOL_ACCESS', 'WEBHOOK_SIGN')),
  CONSTRAINT `ck_p_secret_status` CHECK (`status` IN ('ACTIVE', 'DISABLED', 'DELETED')),
  CONSTRAINT `ck_p_secret_revision` CHECK (`revision` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='平台需可解密的秘密';

-- 账号与接入 / 官方生成及TTS服务
CREATE TABLE IF NOT EXISTS `p_official_service` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '管理员账号',
  `name` varchar(100) COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '服务显示名称',
  `capability` varchar(20) NOT NULL COMMENT 'AVATAR_GENERATION/TTS',
  `provider_code` varchar(64) NOT NULL COMMENT '厂商适配器标识',
  `endpoint` varchar(2048) NOT NULL COMMENT '固定官方API地址',
  `model_id` varchar(128) NOT NULL COMMENT '显式模型版本',
  `secret_id` bigint NOT NULL COMMENT 'p_secret.id',
  `parameters` json NOT NULL COMMENT '非秘密参数，按能力白名单校验',
  `status` varchar(20) NOT NULL COMMENT 'ACTIVE/DISABLED',
  `revision` bigint NOT NULL DEFAULT 1 COMMENT '默认1；服务配置修订号',
  PRIMARY KEY (`id`),
  KEY `idx_p_official_service_1` (`capability`, `status`),
  CONSTRAINT `ck_p_official_service_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_official_service_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_official_service_capability` CHECK (`capability` IN ('AVATAR_GENERATION', 'TTS')),
  CONSTRAINT `ck_p_official_service_secret_id` CHECK (`secret_id` > 0),
  CONSTRAINT `ck_p_official_service_status` CHECK (`status` IN ('ACTIVE', 'DISABLED')),
  CONSTRAINT `ck_p_official_service_revision` CHECK (`revision` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='官方生成及TTS服务';

-- 转接、Voice与Skill / 开发者转接服务
CREATE TABLE IF NOT EXISTS `p_relay_service` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属开发者',
  `name` varchar(100) COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '名称',
  `description` varchar(500) COLLATE utf8mb4_0900_ai_ci NULL COMMENT '描述',
  `status` varchar(20) NOT NULL COMMENT 'ACTIVE/DISABLED/DELETING/DELETED',
  `current_version_id` bigint NULL COMMENT '已发布转接版本',
  `access_secret_id` bigint NOT NULL COMMENT 'p_secret.id；转接Bearer访问凭证',
  `grant_mode` varchar(20) NOT NULL COMMENT 'ALL_ACCOUNT_APPS/EXPLICIT_APPS',
  `auth_epoch` bigint NOT NULL DEFAULT 1 COMMENT '默认1；停用或授权变化递增',
  `last_test_at` datetime(3) NULL COMMENT '最近测试时间',
  `last_test_status` varchar(20) NULL COMMENT 'SUCCESS/FAILED',
  `last_test_error` varchar(64) NULL COMMENT '安全错误码',
  PRIMARY KEY (`id`),
  KEY `idx_p_relay_service_1` (`account_id`, `status`),
  CONSTRAINT `ck_p_relay_service_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_relay_service_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_relay_service_status` CHECK (`status` IN ('ACTIVE', 'DISABLED', 'DELETING', 'DELETED')),
  CONSTRAINT `ck_p_relay_service_current_version_id` CHECK (`current_version_id` > 0),
  CONSTRAINT `ck_p_relay_service_access_secret_id` CHECK (`access_secret_id` > 0),
  CONSTRAINT `ck_p_relay_service_grant_mode` CHECK (`grant_mode` IN ('ALL_ACCOUNT_APPS', 'EXPLICIT_APPS')),
  CONSTRAINT `ck_p_relay_service_auth_epoch` CHECK (`auth_epoch` > 0),
  CONSTRAINT `ck_p_relay_service_last_test_status` CHECK (`last_test_status` IN ('SUCCESS', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='开发者转接服务';

-- 转接、Voice与Skill / 转接配置版本
CREATE TABLE IF NOT EXISTS `p_relay_version` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属开发者',
  `relay_service_id` bigint NOT NULL COMMENT 'p_relay_service.id',
  `version_no` int NOT NULL COMMENT '从1递增',
  `base_url` varchar(2048) NOT NULL COMMENT '开发者后端HTTPS地址',
  `protocol_version` varchar(32) NOT NULL COMMENT '平台转接协议版本',
  `capabilities` json NOT NULL COMMENT 'llm/asr/tts及image/tool/cancel能力声明',
  `endpoints` json NOT NULL COMMENT '各能力相对路径，模型不可改写',
  `timeout_ms` int NOT NULL COMMENT '总调用超时，大于0',
  `max_response_bytes` bigint NOT NULL COMMENT '响应上限，大于0',
  `config_hash` binary(32) NOT NULL COMMENT '规范化非秘密配置摘要',
  `created_by` bigint NOT NULL COMMENT '版本创建者sys_user.user_id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_relay_version_1` (`relay_service_id`, `version_no`),
  KEY `idx_p_relay_version_1` (`account_id`, `relay_service_id`),
  CONSTRAINT `fk_p_relay_version_relay_service_id` FOREIGN KEY (`relay_service_id`) REFERENCES `p_relay_service` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_p_relay_version_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_relay_version_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_relay_version_relay_service_id` CHECK (`relay_service_id` > 0),
  CONSTRAINT `ck_p_relay_version_version_no` CHECK (`version_no` > 0),
  CONSTRAINT `ck_p_relay_version_timeout_ms` CHECK (`timeout_ms` > 0),
  CONSTRAINT `ck_p_relay_version_max_response_bytes` CHECK (`max_response_bytes` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='转接配置版本';

-- 转接、Voice与Skill / 转接服务对应用授权
CREATE TABLE IF NOT EXISTS `p_relay_grant` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属开发者',
  `relay_service_id` bigint NOT NULL COMMENT 'p_relay_service.id',
  `application_id` bigint NOT NULL COMMENT 'p_application.id',
  `scopes` json NOT NULL COMMENT 'LLM/ASR/TTS允许能力',
  `status` varchar(20) NOT NULL COMMENT 'ACTIVE/REVOKED',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_relay_grant_1` (`relay_service_id`, `application_id`),
  KEY `idx_p_relay_grant_1` (`account_id`, `application_id`),
  CONSTRAINT `ck_p_relay_grant_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_relay_grant_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_relay_grant_relay_service_id` CHECK (`relay_service_id` > 0),
  CONSTRAINT `ck_p_relay_grant_application_id` CHECK (`application_id` > 0),
  CONSTRAINT `ck_p_relay_grant_status` CHECK (`status` IN ('ACTIVE', 'REVOKED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='转接服务对应用授权';

-- 资产与版本 / Avatar主表
CREATE TABLE IF NOT EXISTS `p_avatar` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '私有归属账号；官方资源的管理账号',
  `visibility` varchar(16) NOT NULL COMMENT 'PRIVATE/OFFICIAL；不得仅以account_id为空判断公开',
  `name` varchar(100) COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '名称',
  `description` varchar(1000) COLLATE utf8mb4_0900_ai_ci NULL COMMENT '描述',
  `status` varchar(20) NOT NULL COMMENT 'DRAFT/PUBLISHED/UNLISTED/DISABLED/DELETING/DELETED',
  `current_version_id` bigint NULL COMMENT '最新发布版本',
  `revision` bigint NOT NULL DEFAULT 1 COMMENT '默认1；乐观锁与实时状态修订',
  `deleted_at` datetime(3) NULL COMMENT '删除完成时间',
  PRIMARY KEY (`id`),
  KEY `idx_p_avatar_1` (`account_id`, `status`, `created_at`),
  KEY `idx_p_avatar_2` (`visibility`, `status`, `created_at`),
  CONSTRAINT `ck_p_avatar_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_avatar_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_avatar_visibility` CHECK (`visibility` IN ('PRIVATE', 'OFFICIAL')),
  CONSTRAINT `ck_p_avatar_status` CHECK (`status` IN ('DRAFT', 'PUBLISHED', 'UNLISTED', 'DISABLED', 'DELETING', 'DELETED')),
  CONSTRAINT `ck_p_avatar_current_version_id` CHECK (`current_version_id` > 0),
  CONSTRAINT `ck_p_avatar_revision` CHECK (`revision` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='Avatar主表';

-- 资产与版本 / Avatar不可变版本
CREATE TABLE IF NOT EXISTS `p_avatar_version` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT 'Avatar管理账号',
  `avatar_id` bigint NOT NULL COMMENT 'p_avatar.id',
  `version_no` int NOT NULL COMMENT '从1递增',
  `status` varchar(20) NOT NULL COMMENT 'BUILDING/REVIEW/PUBLISHED/REJECTED/DELETING/DELETED',
  `source_type` varchar(20) NOT NULL COMMENT 'IMAGE/VIDEO/OFFICIAL_UPLOAD',
  `source_file_id` bigint NULL COMMENT '原始文件，允许用户独立删除',
  `base_file_id` bigint NULL COMMENT '生成基准图',
  `manifest_file_id` bigint NULL COMMENT '包manifest',
  `preview_file_id` bigint NULL COMMENT '预览图或动画',
  `frame_width` int NULL COMMENT '单帧宽度，发布时必填',
  `frame_height` int NULL COMMENT '单帧高度，发布时必填',
  `anchor_x` decimal(8,6) NULL COMMENT '归一化脚底锚点X，0到1',
  `anchor_y` decimal(8,6) NULL COMMENT '归一化脚底锚点Y，0到1',
  `manifest_schema` varchar(32) NULL COMMENT '包协议版本',
  `pipeline_version` varchar(64) NOT NULL COMMENT '制作流水线版本',
  `generation_recipe` json NOT NULL COMMENT '非秘密模型/参数/提示词版本/参考哈希，长期保留',
  `capabilities` json NOT NULL COMMENT '实际动作及基础speaking声明',
  `qa_report` json NOT NULL COMMENT '结构化几何与人工检查结论，不存素材内容',
  `accepted_by` bigint NULL COMMENT '验收者sys_user.user_id',
  `accepted_at` datetime(3) NULL COMMENT '人工验收时间',
  `published_at` datetime(3) NULL COMMENT '发布时间',
  `created_by` bigint NOT NULL COMMENT '版本创建者sys_user.user_id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_avatar_version_1` (`avatar_id`, `version_no`),
  KEY `idx_p_avatar_version_1` (`account_id`, `avatar_id`, `status`),
  CONSTRAINT `fk_p_avatar_version_avatar_id` FOREIGN KEY (`avatar_id`) REFERENCES `p_avatar` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_p_avatar_version_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_avatar_version_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_avatar_version_avatar_id` CHECK (`avatar_id` > 0),
  CONSTRAINT `ck_p_avatar_version_version_no` CHECK (`version_no` > 0),
  CONSTRAINT `ck_p_avatar_version_status` CHECK (`status` IN ('BUILDING', 'REVIEW', 'PUBLISHED', 'REJECTED', 'DELETING', 'DELETED')),
  CONSTRAINT `ck_p_avatar_version_source_type` CHECK (`source_type` IN ('IMAGE', 'VIDEO', 'OFFICIAL_UPLOAD')),
  CONSTRAINT `ck_p_avatar_version_source_file_id` CHECK (`source_file_id` > 0),
  CONSTRAINT `ck_p_avatar_version_base_file_id` CHECK (`base_file_id` > 0),
  CONSTRAINT `ck_p_avatar_version_manifest_file_id` CHECK (`manifest_file_id` > 0),
  CONSTRAINT `ck_p_avatar_version_preview_file_id` CHECK (`preview_file_id` > 0),
  CONSTRAINT `ck_p_avatar_version_frame_width` CHECK (`frame_width` > 0),
  CONSTRAINT `ck_p_avatar_version_frame_height` CHECK (`frame_height` > 0),
  CONSTRAINT `ck_p_avatar_version_anchor_x` CHECK (`anchor_x` BETWEEN 0 AND 1),
  CONSTRAINT `ck_p_avatar_version_anchor_y` CHECK (`anchor_y` BETWEEN 0 AND 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='Avatar不可变版本';

-- 资产与版本 / 版本内动作
CREATE TABLE IF NOT EXISTS `p_avatar_action` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT 'Avatar管理账号',
  `avatar_version_id` bigint NOT NULL COMMENT 'p_avatar_version.id',
  `action_code` varchar(24) NOT NULL COMMENT '八项固定枚举',
  `atlas_file_id` bigint NOT NULL COMMENT '动作图集对象',
  `preview_file_id` bigint NULL COMMENT '动作预览',
  `frame_count` int NOT NULL COMMENT '正整数；不写死为6',
  `fps` decimal(6,2) NOT NULL COMMENT '正数；实际验证规格',
  `loop_enabled` tinyint NOT NULL DEFAULT 0 COMMENT '默认0；是否循环',
  `frame_layout` json NOT NULL COMMENT '帧坐标/时长/布局；不放图像二进制',
  `content_hash` binary(32) NOT NULL COMMENT '图集或动作manifest摘要',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_avatar_action_1` (`avatar_version_id`, `action_code`),
  KEY `idx_p_avatar_action_1` (`account_id`, `avatar_version_id`),
  CONSTRAINT `fk_p_avatar_action_avatar_version_id` FOREIGN KEY (`avatar_version_id`) REFERENCES `p_avatar_version` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_p_avatar_action_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_avatar_action_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_avatar_action_avatar_version_id` CHECK (`avatar_version_id` > 0),
  CONSTRAINT `ck_p_avatar_action_action_code` CHECK (`action_code` IN ('idle', 'speaking', 'listening', 'thinking', 'nod', 'shake_head', 'wave', 'happy')),
  CONSTRAINT `ck_p_avatar_action_atlas_file_id` CHECK (`atlas_file_id` > 0),
  CONSTRAINT `ck_p_avatar_action_preview_file_id` CHECK (`preview_file_id` > 0),
  CONSTRAINT `ck_p_avatar_action_frame_count` CHECK (`frame_count` > 0),
  CONSTRAINT `ck_p_avatar_action_fps` CHECK (`fps` > 0),
  CONSTRAINT `ck_p_avatar_action_loop_enabled` CHECK (`loop_enabled` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='版本内动作';

-- 资产与版本 / Voice主表
CREATE TABLE IF NOT EXISTS `p_voice` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '私有归属账号；官方资源的管理账号',
  `visibility` varchar(16) NOT NULL COMMENT 'PRIVATE/OFFICIAL；不得仅以account_id为空判断公开',
  `name` varchar(100) COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '名称',
  `description` varchar(1000) COLLATE utf8mb4_0900_ai_ci NULL COMMENT '描述',
  `status` varchar(20) NOT NULL COMMENT 'DRAFT/PUBLISHED/UNLISTED/DISABLED/DELETING/DELETED',
  `current_version_id` bigint NULL COMMENT '最新发布版本',
  `revision` bigint NOT NULL DEFAULT 1 COMMENT '默认1；乐观锁与实时状态修订',
  `deleted_at` datetime(3) NULL COMMENT '删除完成时间',
  PRIMARY KEY (`id`),
  KEY `idx_p_voice_1` (`account_id`, `status`, `created_at`),
  KEY `idx_p_voice_2` (`visibility`, `status`, `created_at`),
  CONSTRAINT `ck_p_voice_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_voice_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_voice_visibility` CHECK (`visibility` IN ('PRIVATE', 'OFFICIAL')),
  CONSTRAINT `ck_p_voice_status` CHECK (`status` IN ('DRAFT', 'PUBLISHED', 'UNLISTED', 'DISABLED', 'DELETING', 'DELETED')),
  CONSTRAINT `ck_p_voice_current_version_id` CHECK (`current_version_id` > 0),
  CONSTRAINT `ck_p_voice_revision` CHECK (`revision` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='Voice主表';

-- 资产与版本 / Voice配置版本
CREATE TABLE IF NOT EXISTS `p_voice_version` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT 'Voice管理账号',
  `voice_id` bigint NOT NULL COMMENT 'p_voice.id',
  `version_no` int NOT NULL COMMENT '从1递增',
  `service_type` varchar(16) NOT NULL COMMENT 'OFFICIAL/RELAY',
  `official_service_id` bigint NULL COMMENT '官方TTS服务',
  `relay_version_id` bigint NULL COMMENT '开发者TTS转接版本',
  `voice_code` varchar(128) NOT NULL COMMENT '厂商或转接音色别名',
  `language_code` varchar(32) NULL COMMENT '语言标识',
  `model_id` varchar(128) NULL COMMENT '可选显式模型',
  `parameters` json NOT NULL COMMENT '音速等白名单非秘密参数',
  `official_config_snapshot` json NULL COMMENT '官方服务非秘密配置，含secret_id引用',
  `sample_file_id` bigint NULL COMMENT '官方/自有音色演示音频，不是会话临时音频',
  `created_by` bigint NOT NULL COMMENT '版本创建者sys_user.user_id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_voice_version_1` (`voice_id`, `version_no`),
  KEY `idx_p_voice_version_1` (`account_id`, `voice_id`),
  CONSTRAINT `fk_p_voice_version_voice_id` FOREIGN KEY (`voice_id`) REFERENCES `p_voice` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  KEY `idx_p_voice_version_fk_relay_version_id` (`relay_version_id`),
  CONSTRAINT `fk_p_voice_version_relay_version_id` FOREIGN KEY (`relay_version_id`) REFERENCES `p_relay_version` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_p_voice_version_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_voice_version_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_voice_version_voice_id` CHECK (`voice_id` > 0),
  CONSTRAINT `ck_p_voice_version_version_no` CHECK (`version_no` > 0),
  CONSTRAINT `ck_p_voice_version_service_type` CHECK (`service_type` IN ('OFFICIAL', 'RELAY')),
  CONSTRAINT `ck_p_voice_version_official_service_id` CHECK (`official_service_id` > 0),
  CONSTRAINT `ck_p_voice_version_relay_version_id` CHECK (`relay_version_id` > 0),
  CONSTRAINT `ck_p_voice_version_sample_file_id` CHECK (`sample_file_id` > 0),
  CONSTRAINT `ck_p_voice_version_service_reference` CHECK ((`service_type` = 'OFFICIAL' AND `official_service_id` IS NOT NULL AND `relay_version_id` IS NULL) OR (`service_type` = 'RELAY' AND `relay_version_id` IS NOT NULL AND `official_service_id` IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='Voice配置版本';

-- 资产与版本 / Skill主表
CREATE TABLE IF NOT EXISTS `p_skill` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '私有归属账号；官方资源的管理账号',
  `visibility` varchar(16) NOT NULL COMMENT 'PRIVATE/OFFICIAL；不得仅以account_id为空判断公开',
  `name` varchar(100) COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '名称',
  `description` varchar(1000) COLLATE utf8mb4_0900_ai_ci NULL COMMENT '描述',
  `status` varchar(20) NOT NULL COMMENT 'DRAFT/PUBLISHED/UNLISTED/DISABLED/DELETING/DELETED',
  `current_version_id` bigint NULL COMMENT '最新发布版本',
  `revision` bigint NOT NULL DEFAULT 1 COMMENT '默认1；乐观锁与实时状态修订',
  `deleted_at` datetime(3) NULL COMMENT '删除完成时间',
  PRIMARY KEY (`id`),
  KEY `idx_p_skill_1` (`account_id`, `status`, `created_at`),
  KEY `idx_p_skill_2` (`visibility`, `status`, `created_at`),
  CONSTRAINT `ck_p_skill_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_skill_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_skill_visibility` CHECK (`visibility` IN ('PRIVATE', 'OFFICIAL')),
  CONSTRAINT `ck_p_skill_status` CHECK (`status` IN ('DRAFT', 'PUBLISHED', 'UNLISTED', 'DISABLED', 'DELETING', 'DELETED')),
  CONSTRAINT `ck_p_skill_current_version_id` CHECK (`current_version_id` > 0),
  CONSTRAINT `ck_p_skill_revision` CHECK (`revision` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='Skill主表';

-- 资产与版本 / Prompt或Tool版本
CREATE TABLE IF NOT EXISTS `p_skill_version` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT 'Skill管理账号',
  `skill_id` bigint NOT NULL COMMENT 'p_skill.id',
  `version_no` int NOT NULL COMMENT '从1递增',
  `skill_type` varchar(16) NOT NULL COMMENT 'PROMPT/HTTP_TOOL',
  `tool_name` varchar(64) NULL COMMENT 'Tool调用名称',
  `instructions` mediumtext NULL COMMENT 'Prompt正文',
  `context_requirements` json NOT NULL COMMENT '需要的Context范围/模式',
  `tool_url` varchar(2048) NULL COMMENT '固定查询地址',
  `http_method` varchar(8) NULL COMMENT 'GET/POST',
  `input_schema` json NULL COMMENT '参数JSON Schema',
  `output_schema` json NULL COMMENT '返回数据约定',
  `tool_secret_id` bigint NULL COMMENT 'p_secret.id；接口凭证引用',
  `requires_user_credential` tinyint NOT NULL DEFAULT 0 COMMENT '默认0；是否需要业务用户短期凭证',
  `identity_binding` json NULL COMMENT '用户身份注入到固定header/body字段的规则',
  `frontend_fields` json NULL DEFAULT (JSON_ARRAY()) COMMENT '允许返回前端的结果字段白名单；默认空',
  `timeout_ms` int NULL COMMENT '工具超时',
  `max_result_bytes` bigint NULL COMMENT '工具原始结果上限',
  `import_format` varchar(32) NULL COMMENT '导入格式来源',
  `content_hash` binary(32) NOT NULL COMMENT '规范化定义摘要',
  `created_by` bigint NOT NULL COMMENT '版本创建者sys_user.user_id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_skill_version_1` (`skill_id`, `version_no`),
  KEY `idx_p_skill_version_1` (`account_id`, `skill_id`),
  CONSTRAINT `fk_p_skill_version_skill_id` FOREIGN KEY (`skill_id`) REFERENCES `p_skill` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_p_skill_version_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_skill_version_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_skill_version_skill_id` CHECK (`skill_id` > 0),
  CONSTRAINT `ck_p_skill_version_version_no` CHECK (`version_no` > 0),
  CONSTRAINT `ck_p_skill_version_skill_type` CHECK (`skill_type` IN ('PROMPT', 'HTTP_TOOL')),
  CONSTRAINT `ck_p_skill_version_http_method` CHECK (`http_method` IN ('GET', 'POST')),
  CONSTRAINT `ck_p_skill_version_tool_secret_id` CHECK (`tool_secret_id` > 0),
  CONSTRAINT `ck_p_skill_version_requires_user_credential` CHECK (`requires_user_credential` IN (0, 1)),
  CONSTRAINT `ck_p_skill_version_timeout_ms` CHECK (`timeout_ms` > 0),
  CONSTRAINT `ck_p_skill_version_max_result_bytes` CHECK (`max_result_bytes` > 0),
  CONSTRAINT `ck_p_skill_version_definition` CHECK ((`skill_type` = 'PROMPT' AND `instructions` IS NOT NULL) OR (`skill_type` = 'HTTP_TOOL' AND `tool_name` IS NOT NULL AND `tool_url` IS NOT NULL AND `http_method` IS NOT NULL AND `input_schema` IS NOT NULL AND `output_schema` IS NOT NULL AND `timeout_ms` IS NOT NULL AND `max_result_bytes` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='Prompt或Tool版本';

-- 应用与引用 / Application与当前授权
CREATE TABLE IF NOT EXISTS `p_application` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属开发者',
  `name` varchar(100) COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '名称',
  `description` varchar(1000) COLLATE utf8mb4_0900_ai_ci NULL COMMENT '描述',
  `status` varchar(20) NOT NULL COMMENT 'ACTIVE/DISABLED/DELETING/DELETED',
  `current_config_id` bigint NULL COMMENT '已发布配置版本',
  `current_policy` json NOT NULL COMMENT '当前实时权限上限；与配置快照求交集',
  `auth_epoch` bigint NOT NULL DEFAULT 1 COMMENT '默认1；撤权/停用递增',
  `revision` bigint NOT NULL DEFAULT 1 COMMENT '默认1；配置发布乐观锁',
  `deleted_at` datetime(3) NULL COMMENT '删除完成时间',
  PRIMARY KEY (`id`),
  KEY `idx_p_application_1` (`account_id`, `status`, `created_at`),
  CONSTRAINT `ck_p_application_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_application_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_application_status` CHECK (`status` IN ('ACTIVE', 'DISABLED', 'DELETING', 'DELETED')),
  CONSTRAINT `ck_p_application_current_config_id` CHECK (`current_config_id` > 0),
  CONSTRAINT `ck_p_application_auth_epoch` CHECK (`auth_epoch` > 0),
  CONSTRAINT `ck_p_application_revision` CHECK (`revision` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='Application与当前授权';

-- 应用与引用 / Application不可变配置
CREATE TABLE IF NOT EXISTS `p_app_config` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属开发者',
  `application_id` bigint NOT NULL COMMENT 'p_application.id',
  `version_no` int NOT NULL COMMENT '从1递增',
  `mode` varchar(16) NOT NULL COMMENT 'CHAT/SPEAK_ONLY',
  `avatar_version_id` bigint NOT NULL COMMENT '一个已发布Avatar版本',
  `voice_version_id` bigint NULL COMMENT '可选Voice',
  `llm_relay_version_id` bigint NULL COMMENT 'CHAT必填',
  `asr_relay_version_id` bigint NULL COMMENT '录音识别能力可选',
  `llm_model_id` varchar(128) NULL COMMENT 'CHAT必填',
  `system_prompt` mediumtext NULL COMMENT 'Application人设',
  `llm_parameters` json NULL COMMENT '温度/输出上限等支持的参数',
  `llm_capabilities` json NULL COMMENT '图片/工具能力声明',
  `context_policy` json NOT NULL COMMENT 'Element/Page、allow/deny、显式或AI、全页、严格模式、高亮规则',
  `runtime_limits` json NOT NULL COMMENT '历史轮数/输入预算/每轮工具采集次数/超时等生效值',
  `config_hash` binary(32) NOT NULL COMMENT '规范化配置摘要',
  `published_at` datetime(3) NOT NULL COMMENT '发布时间',
  `created_by` bigint NOT NULL COMMENT '版本创建者sys_user.user_id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_app_config_1` (`application_id`, `version_no`),
  KEY `idx_p_app_config_1` (`account_id`, `application_id`),
  CONSTRAINT `fk_p_app_config_application_id` FOREIGN KEY (`application_id`) REFERENCES `p_application` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  KEY `idx_p_app_config_fk_avatar_version_id` (`avatar_version_id`),
  CONSTRAINT `fk_p_app_config_avatar_version_id` FOREIGN KEY (`avatar_version_id`) REFERENCES `p_avatar_version` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  KEY `idx_p_app_config_fk_voice_version_id` (`voice_version_id`),
  CONSTRAINT `fk_p_app_config_voice_version_id` FOREIGN KEY (`voice_version_id`) REFERENCES `p_voice_version` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  KEY `idx_p_app_config_fk_llm_relay_version_id` (`llm_relay_version_id`),
  CONSTRAINT `fk_p_app_config_llm_relay_version_id` FOREIGN KEY (`llm_relay_version_id`) REFERENCES `p_relay_version` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  KEY `idx_p_app_config_fk_asr_relay_version_id` (`asr_relay_version_id`),
  CONSTRAINT `fk_p_app_config_asr_relay_version_id` FOREIGN KEY (`asr_relay_version_id`) REFERENCES `p_relay_version` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_p_app_config_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_app_config_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_app_config_application_id` CHECK (`application_id` > 0),
  CONSTRAINT `ck_p_app_config_version_no` CHECK (`version_no` > 0),
  CONSTRAINT `ck_p_app_config_mode` CHECK (`mode` IN ('CHAT', 'SPEAK_ONLY')),
  CONSTRAINT `ck_p_app_config_avatar_version_id` CHECK (`avatar_version_id` > 0),
  CONSTRAINT `ck_p_app_config_voice_version_id` CHECK (`voice_version_id` > 0),
  CONSTRAINT `ck_p_app_config_llm_relay_version_id` CHECK (`llm_relay_version_id` > 0),
  CONSTRAINT `ck_p_app_config_asr_relay_version_id` CHECK (`asr_relay_version_id` > 0),
  CONSTRAINT `ck_p_app_config_mode_config` CHECK ((`mode` = 'CHAT' AND `llm_relay_version_id` IS NOT NULL AND `llm_model_id` IS NOT NULL) OR (`mode` = 'SPEAK_ONLY' AND `voice_version_id` IS NOT NULL AND `llm_relay_version_id` IS NULL AND `llm_model_id` IS NULL AND `llm_parameters` IS NULL AND `llm_capabilities` IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='Application不可变配置';

-- 应用与引用 / 配置绑定Skill及顺序
CREATE TABLE IF NOT EXISTS `p_app_skill` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属开发者',
  `app_config_id` bigint NOT NULL COMMENT 'p_app_config.id',
  `skill_version_id` bigint NOT NULL COMMENT 'p_skill_version.id',
  `enabled` tinyint NOT NULL DEFAULT 1 COMMENT '默认1',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '默认0；升序，同值按id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_app_skill_1` (`app_config_id`, `skill_version_id`),
  KEY `idx_p_app_skill_1` (`account_id`, `app_config_id`, `sort_order`),
  CONSTRAINT `fk_p_app_skill_app_config_id` FOREIGN KEY (`app_config_id`) REFERENCES `p_app_config` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  KEY `idx_p_app_skill_fk_skill_version_id` (`skill_version_id`),
  CONSTRAINT `fk_p_app_skill_skill_version_id` FOREIGN KEY (`skill_version_id`) REFERENCES `p_skill_version` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_p_app_skill_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_app_skill_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_app_skill_app_config_id` CHECK (`app_config_id` > 0),
  CONSTRAINT `ck_p_app_skill_skill_version_id` CHECK (`skill_version_id` > 0),
  CONSTRAINT `ck_p_app_skill_enabled` CHECK (`enabled` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='配置绑定Skill及顺序';

-- 应用与引用 / 资产绑定与跨库引用预留
CREATE TABLE IF NOT EXISTS `p_resource_reference` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '引用者账号；可与官方资源管理账号不同',
  `holder_type` varchar(24) NOT NULL COMMENT 'APP_CURRENT/SESSION/GENERATION',
  `holder_id` bigint NOT NULL COMMENT '应用/Session/任务ID',
  `operation_id` varchar(64) NOT NULL COMMENT '引用操作幂等标识',
  `resource_type` varchar(24) NOT NULL COMMENT 'APP_CONFIG/AVATAR_VERSION/VOICE_VERSION/SKILL_VERSION/RELAY_VERSION',
  `resource_id` bigint NOT NULL COMMENT '对应资源版本ID',
  `state` varchar(20) NOT NULL COMMENT 'RESERVED/CONFIRMED/RELEASED',
  `lease_expires_at` datetime(3) NULL COMMENT '待核对时间，非自动释放依据',
  `confirmed_at` datetime(3) NULL COMMENT '确认时间',
  `released_at` datetime(3) NULL COMMENT '释放时间',
  `next_check_at` datetime(3) NULL COMMENT '补偿核对时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_resource_reference_1` (`holder_type`, `holder_id`, `resource_type`, `resource_id`),
  KEY `idx_p_resource_reference_1` (`resource_type`, `resource_id`, `state`),
  KEY `idx_p_resource_reference_2` (`state`, `next_check_at`),
  KEY `idx_p_resource_reference_3` (`account_id`, `holder_type`, `holder_id`),
  CONSTRAINT `ck_p_resource_reference_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_resource_reference_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_resource_reference_holder_type` CHECK (`holder_type` IN ('APP_CURRENT', 'SESSION', 'GENERATION')),
  CONSTRAINT `ck_p_resource_reference_holder_id` CHECK (`holder_id` > 0),
  CONSTRAINT `ck_p_resource_reference_resource_type` CHECK (`resource_type` IN ('APP_CONFIG', 'AVATAR_VERSION', 'VOICE_VERSION', 'SKILL_VERSION', 'RELAY_VERSION')),
  CONSTRAINT `ck_p_resource_reference_resource_id` CHECK (`resource_id` > 0),
  CONSTRAINT `ck_p_resource_reference_state` CHECK (`state` IN ('RESERVED', 'CONFIRMED', 'RELEASED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='资产绑定与跨库引用预留';

-- 文件与生成任务 / 长期资产与上传元数据
CREATE TABLE IF NOT EXISTS `p_file` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属账号',
  `purpose` varchar(24) NOT NULL COMMENT 'AVATAR_SOURCE/BASE/ATLAS/MANIFEST/PREVIEW/VOICE_SAMPLE/ACCOUNT_ICON（数据库设计§4.2补充）',
  `storage_provider` varchar(32) NOT NULL COMMENT '云存储适配器',
  `bucket` varchar(128) NOT NULL COMMENT '桶标识',
  `object_key` varchar(768) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '平台生成的ASCII对象键，不是签名URL',
  `original_name` varchar(255) COLLATE utf8mb4_0900_ai_ci NULL COMMENT '原始文件名',
  `content_type` varchar(128) NOT NULL COMMENT '实测媒体类型',
  `size_bytes` bigint NOT NULL COMMENT '文件字节数',
  `sha256` binary(32) NULL COMMENT '上传完成核验摘要',
  `width` int NULL COMMENT '图片宽度',
  `height` int NULL COMMENT '图片高度',
  `duration_ms` bigint NULL COMMENT '音视频时长',
  `status` varchar(20) NOT NULL COMMENT 'UPLOADING/AVAILABLE/DELETE_PENDING/DELETED/FAILED',
  `storage_reservation_id` bigint NULL COMMENT 'p_quota_reservation.id',
  `upload_expires_at` datetime(3) NULL COMMENT '未完成上传回收时间',
  `delete_after` datetime(3) NULL COMMENT '下次删除扫描时间',
  `rights_notice_version` varchar(32) NULL COMMENT '真人素材弹窗版本',
  `rights_confirmed_at` datetime(3) NULL COMMENT '上传者确认时间',
  `confirmed_by` bigint NULL COMMENT '确认账号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_file_1` (`storage_provider`, `bucket`, `object_key`),
  KEY `idx_p_file_1` (`account_id`, `status`, `created_at`),
  KEY `idx_p_file_2` (`status`, `delete_after`),
  KEY `idx_p_file_3` (`status`, `upload_expires_at`),
  CONSTRAINT `ck_p_file_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_file_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_file_purpose` CHECK (`purpose` IN ('AVATAR_SOURCE', 'BASE', 'ATLAS', 'MANIFEST', 'PREVIEW', 'VOICE_SAMPLE', 'ACCOUNT_ICON')),
  CONSTRAINT `ck_p_file_size_bytes` CHECK (`size_bytes` >= 0),
  CONSTRAINT `ck_p_file_width` CHECK (`width` > 0),
  CONSTRAINT `ck_p_file_height` CHECK (`height` > 0),
  CONSTRAINT `ck_p_file_duration_ms` CHECK (`duration_ms` >= 0),
  CONSTRAINT `ck_p_file_status` CHECK (`status` IN ('UPLOADING', 'AVAILABLE', 'DELETE_PENDING', 'DELETED', 'FAILED')),
  CONSTRAINT `ck_p_file_storage_reservation_id` CHECK (`storage_reservation_id` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='长期资产与上传元数据';

-- 文件与生成任务 / 一次完整制作任务
CREATE TABLE IF NOT EXISTS `p_generation_task` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属账号',
  `avatar_id` bigint NOT NULL COMMENT '目标Avatar',
  `avatar_version_id` bigint NOT NULL COMMENT '目标未发布版本',
  `source_file_id` bigint NULL COMMENT '输入文件',
  `task_kind` varchar(24) NOT NULL COMMENT 'GENERATE/REGENERATE',
  `status` varchar(20) NOT NULL COMMENT 'QUEUED/PROCESSING/SUCCEEDED/FAILED',
  `internal_state` varchar(24) NOT NULL COMMENT 'READY/RUNNING/REVIEW_REQUIRED/FINISHED',
  `progress` smallint NOT NULL COMMENT '0到100',
  `official_service_id` bigint NOT NULL COMMENT '官方生成服务',
  `service_snapshot` json NOT NULL COMMENT '非秘密端点/模型/参数与secret_id引用',
  `pipeline_version` varchar(64) NOT NULL COMMENT '流水线版本',
  `quota_reservation_id` bigint NOT NULL COMMENT '一整套生成次数预占',
  `request_id` varchar(64) NOT NULL COMMENT '用户提交幂等ID',
  `retry_of_task_id` bigint NULL COMMENT '失败任务恢复来源，非成功重生成',
  `error_code` varchar(64) NULL COMMENT '安全错误码',
  `error_message` varchar(500) NULL COMMENT '脱敏说明',
  `started_at` datetime(3) NULL COMMENT '开始时间',
  `finished_at` datetime(3) NULL COMMENT '最终结束时间',
  `expires_at` datetime(3) NULL COMMENT '终态30天清理时间',
  `webhook_endpoint_id` bigint NULL COMMENT '提交时选择的账号Webhook，可空',
  `reservation_no` int NOT NULL DEFAULT 1 COMMENT '默认1；用户显式重试已释放任务时递增',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_generation_task_1` (`account_id`, `request_id`),
  KEY `idx_p_generation_task_1` (`account_id`, `status`, `created_at`),
  KEY `idx_p_generation_task_2` (`status`, `created_at`),
  KEY `idx_p_generation_task_3` (`expires_at`),
  CONSTRAINT `ck_p_generation_task_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_generation_task_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_generation_task_avatar_id` CHECK (`avatar_id` > 0),
  CONSTRAINT `ck_p_generation_task_avatar_version_id` CHECK (`avatar_version_id` > 0),
  CONSTRAINT `ck_p_generation_task_source_file_id` CHECK (`source_file_id` > 0),
  CONSTRAINT `ck_p_generation_task_task_kind` CHECK (`task_kind` IN ('GENERATE', 'REGENERATE')),
  CONSTRAINT `ck_p_generation_task_status` CHECK (`status` IN ('QUEUED', 'PROCESSING', 'SUCCEEDED', 'FAILED')),
  CONSTRAINT `ck_p_generation_task_internal_state` CHECK (`internal_state` IN ('READY', 'RUNNING', 'REVIEW_REQUIRED', 'FINISHED')),
  CONSTRAINT `ck_p_generation_task_official_service_id` CHECK (`official_service_id` > 0),
  CONSTRAINT `ck_p_generation_task_quota_reservation_id` CHECK (`quota_reservation_id` > 0),
  CONSTRAINT `ck_p_generation_task_retry_of_task_id` CHECK (`retry_of_task_id` > 0),
  CONSTRAINT `ck_p_generation_task_webhook_endpoint_id` CHECK (`webhook_endpoint_id` > 0),
  CONSTRAINT `ck_p_generation_task_reservation_no` CHECK (`reservation_no` > 0),
  CONSTRAINT `ck_p_generation_task_progress` CHECK (`progress` BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='一次完整制作任务';

-- 文件与生成任务 / 制作步骤及Worker租约
CREATE TABLE IF NOT EXISTS `p_generation_step` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属账号',
  `task_id` bigint NOT NULL COMMENT 'p_generation_task.id',
  `step_key` varchar(64) NOT NULL COMMENT 'SOURCE/BASE/ACTION_idle等/PACKAGE/QA',
  `step_type` varchar(24) NOT NULL COMMENT 'EXTRACT_REFERENCE/GENERATE_BASE/GENERATE_ACTION/PACKAGE/QA',
  `action_code` varchar(24) NULL COMMENT '固定动作代码',
  `depends_on` json NOT NULL COMMENT '前置step_key数组；同任务内无环',
  `status` varchar(24) NOT NULL COMMENT 'WAITING/READY/RUNNING/POLLING/UNKNOWN/SUCCEEDED/FAILED',
  `attempt_no` int NOT NULL DEFAULT 0 COMMENT '默认0；已分配执行次数',
  `result_file_id` bigint NULL COMMENT '主要输出',
  `result_metadata` json NULL COMMENT '非秘密QA或产物引用',
  `lease_owner` varchar(128) NULL COMMENT 'Worker标识',
  `lease_epoch` bigint NOT NULL DEFAULT 0 COMMENT '默认0；每次领取递增',
  `lease_expires_at` datetime(3) NULL COMMENT '租约截止',
  `heartbeat_at` datetime(3) NULL COMMENT '最近心跳',
  `next_run_at` datetime(3) NULL COMMENT '下一调度时间',
  `error_code` varchar(64) NULL COMMENT '安全错误码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_generation_step_1` (`task_id`, `step_key`),
  KEY `idx_p_generation_step_1` (`status`, `next_run_at`),
  KEY `idx_p_generation_step_2` (`status`, `lease_expires_at`),
  KEY `idx_p_generation_step_3` (`account_id`, `task_id`),
  CONSTRAINT `fk_p_generation_step_task_id` FOREIGN KEY (`task_id`) REFERENCES `p_generation_task` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_p_generation_step_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_generation_step_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_generation_step_task_id` CHECK (`task_id` > 0),
  CONSTRAINT `ck_p_generation_step_step_type` CHECK (`step_type` IN ('EXTRACT_REFERENCE', 'GENERATE_BASE', 'GENERATE_ACTION', 'PACKAGE', 'QA')),
  CONSTRAINT `ck_p_generation_step_action_code` CHECK (`action_code` IN ('idle', 'speaking', 'listening', 'thinking', 'nod', 'shake_head', 'wave', 'happy')),
  CONSTRAINT `ck_p_generation_step_status` CHECK (`status` IN ('WAITING', 'READY', 'RUNNING', 'POLLING', 'UNKNOWN', 'SUCCEEDED', 'FAILED')),
  CONSTRAINT `ck_p_generation_step_attempt_no` CHECK (`attempt_no` >= 0),
  CONSTRAINT `ck_p_generation_step_result_file_id` CHECK (`result_file_id` > 0),
  CONSTRAINT `ck_p_generation_step_lease_epoch` CHECK (`lease_epoch` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='制作步骤及Worker租约';

-- 文件与生成任务 / 实际API尝试与核对
CREATE TABLE IF NOT EXISTS `p_generation_attempt` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数 ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属账号',
  `task_id` bigint NOT NULL COMMENT 'p_generation_task.id',
  `step_id` bigint NOT NULL COMMENT 'p_generation_step.id',
  `attempt_no` int NOT NULL COMMENT '步骤内递增',
  `lease_epoch` bigint NOT NULL COMMENT '执行租约代数',
  `provider_request_key` varchar(64) NOT NULL COMMENT '发出前持久生成，厂商支持时用于幂等',
  `provider_request_id` varchar(128) NULL COMMENT '厂商返回请求ID',
  `provider_task_id` varchar(128) NULL COMMENT '异步任务ID',
  `model_id` varchar(128) NOT NULL COMMENT '本次模型',
  `status` varchar(24) NOT NULL COMMENT 'PREPARED/SUBMITTED/UNKNOWN/SUCCEEDED/FAILED',
  `request_hash` binary(32) NOT NULL COMMENT '非秘密请求摘要',
  `output_file_id` bigint NULL COMMENT '主要返回文件',
  `submitted_at` datetime(3) NULL COMMENT '提交时间',
  `completed_at` datetime(3) NULL COMMENT '完成时间',
  `reviewed_by` bigint NULL COMMENT '人工核对人',
  `reviewed_at` datetime(3) NULL COMMENT '核对时间',
  `review_note` varchar(500) NULL COMMENT '脱敏核对依据',
  `error_code` varchar(64) NULL COMMENT '安全错误码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_generation_attempt_1` (`step_id`, `attempt_no`),
  UNIQUE KEY `uq_p_generation_attempt_2` (`provider_request_key`),
  KEY `idx_p_generation_attempt_1` (`status`, `submitted_at`),
  KEY `idx_p_generation_attempt_2` (`account_id`, `task_id`),
  CONSTRAINT `fk_p_generation_attempt_step_id` FOREIGN KEY (`step_id`) REFERENCES `p_generation_step` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_p_generation_attempt_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_generation_attempt_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_generation_attempt_task_id` CHECK (`task_id` > 0),
  CONSTRAINT `ck_p_generation_attempt_step_id` CHECK (`step_id` > 0),
  CONSTRAINT `ck_p_generation_attempt_attempt_no` CHECK (`attempt_no` > 0),
  CONSTRAINT `ck_p_generation_attempt_lease_epoch` CHECK (`lease_epoch` >= 0),
  CONSTRAINT `ck_p_generation_attempt_status` CHECK (`status` IN ('PREPARED', 'SUBMITTED', 'UNKNOWN', 'SUCCEEDED', 'FAILED')),
  CONSTRAINT `ck_p_generation_attempt_output_file_id` CHECK (`output_file_id` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='实际API尝试与核对';

-- 额度与用量 / 账号运行上限
CREATE TABLE IF NOT EXISTS `p_account_limit` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属账号',
  `max_file_bytes` bigint NOT NULL COMMENT '单文件上限',
  `max_sessions` int NOT NULL COMMENT '同时活跃Session上限',
  `max_generation_tasks` int NOT NULL COMMENT '并行生成任务上限',
  `max_turns` int NOT NULL COMMENT '全账号并发轮次上限',
  `revision` bigint NOT NULL DEFAULT 1 COMMENT '默认1；修改修订号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_account_limit_1` (`account_id`),
  CONSTRAINT `ck_p_account_limit_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_account_limit_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_account_limit_max_file_bytes` CHECK (`max_file_bytes` >= 0),
  CONSTRAINT `ck_p_account_limit_max_sessions` CHECK (`max_sessions` >= 0),
  CONSTRAINT `ck_p_account_limit_max_generation_tasks` CHECK (`max_generation_tasks` >= 0),
  CONSTRAINT `ck_p_account_limit_max_turns` CHECK (`max_turns` >= 0),
  CONSTRAINT `ck_p_account_limit_revision` CHECK (`revision` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='账号运行上限';

-- 额度与用量 / 账号分类额度余额
CREATE TABLE IF NOT EXISTS `p_quota_balance` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属账号',
  `quota_type` varchar(24) NOT NULL COMMENT 'AVATAR_COUNT/TTS_CHAR/STORAGE_BYTE',
  `granted_units` bigint NOT NULL COMMENT '管理员累计授予额度',
  `used_units` bigint NOT NULL COMMENT '已用；存储表示当前已占用字节',
  `reserved_units` bigint NOT NULL COMMENT '正在预占',
  `revision` bigint NOT NULL DEFAULT 1 COMMENT '默认1；并发更新版本',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_quota_balance_1` (`account_id`, `quota_type`),
  CONSTRAINT `ck_p_quota_balance_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_quota_balance_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_quota_balance_quota_type` CHECK (`quota_type` IN ('AVATAR_COUNT', 'TTS_CHAR', 'STORAGE_BYTE')),
  CONSTRAINT `ck_p_quota_balance_granted_units` CHECK (`granted_units` >= 0),
  CONSTRAINT `ck_p_quota_balance_used_units` CHECK (`used_units` >= 0),
  CONSTRAINT `ck_p_quota_balance_reserved_units` CHECK (`reserved_units` >= 0),
  CONSTRAINT `ck_p_quota_balance_revision` CHECK (`revision` > 0),
  CONSTRAINT `ck_p_quota_balance_capacity` CHECK (`used_units` <= `granted_units` AND `reserved_units` <= `granted_units` - `used_units`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='账号分类额度余额';

-- 额度与用量 / 额度预占与结算
CREATE TABLE IF NOT EXISTS `p_quota_reservation` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属账号',
  `quota_type` varchar(24) NOT NULL COMMENT 'AVATAR_COUNT/TTS_CHAR/STORAGE_BYTE',
  `business_type` varchar(24) NOT NULL COMMENT 'GENERATION/TTS_SEGMENT/UPLOAD',
  `business_id` varchar(128) NOT NULL COMMENT '任务ID、turn_id:segment_id或file_id',
  `reservation_no` int NOT NULL DEFAULT 1 COMMENT '默认1；失败释放后显式重试递增',
  `reserved_units` bigint NOT NULL COMMENT '本次预占整数',
  `settled_units` bigint NOT NULL DEFAULT 0 COMMENT '默认0；实际结算量',
  `state` varchar(20) NOT NULL COMMENT 'RESERVED/SETTLED/RELEASED/REVIEW_REQUIRED',
  `expires_at` datetime(3) NULL COMMENT '触发核对，不自动退款',
  `settled_at` datetime(3) NULL COMMENT '最终结算时间',
  `released_at` datetime(3) NULL COMMENT '最终释放时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_quota_reservation_1` (`account_id`, `quota_type`, `business_type`, `business_id`, `reservation_no`),
  KEY `idx_p_quota_reservation_1` (`state`, `expires_at`),
  KEY `idx_p_quota_reservation_2` (`account_id`, `created_at`),
  CONSTRAINT `ck_p_quota_reservation_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_quota_reservation_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_quota_reservation_quota_type` CHECK (`quota_type` IN ('AVATAR_COUNT', 'TTS_CHAR', 'STORAGE_BYTE')),
  CONSTRAINT `ck_p_quota_reservation_business_type` CHECK (`business_type` IN ('GENERATION', 'TTS_SEGMENT', 'UPLOAD')),
  CONSTRAINT `ck_p_quota_reservation_reservation_no` CHECK (`reservation_no` > 0),
  CONSTRAINT `ck_p_quota_reservation_reserved_units` CHECK (`reserved_units` >= 0),
  CONSTRAINT `ck_p_quota_reservation_settled_units` CHECK (`settled_units` >= 0),
  CONSTRAINT `ck_p_quota_reservation_state` CHECK (`state` IN ('RESERVED', 'SETTLED', 'RELEASED', 'REVIEW_REQUIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='额度预占与结算';

-- 额度与用量 / 额度不可变流水
CREATE TABLE IF NOT EXISTS `p_quota_entry` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属账号',
  `quota_type` varchar(24) NOT NULL COMMENT '额度类别',
  `reservation_id` bigint NULL COMMENT '预占ID；管理员调整可空',
  `event_key` varchar(128) NOT NULL COMMENT '业务结算/调整唯一标识',
  `entry_type` varchar(24) NOT NULL COMMENT 'GRANT/RESERVE/SETTLE/RELEASE/STORAGE_FREE/ADJUST',
  `delta_granted` bigint NOT NULL COMMENT '授予额度变化量',
  `delta_used` bigint NOT NULL COMMENT '使用额度变化量',
  `delta_reserved` bigint NOT NULL COMMENT '预占变化量',
  `operator_id` bigint NULL COMMENT '人工操作账号',
  `reason` varchar(500) NULL COMMENT '调整依据',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_quota_entry_1` (`account_id`, `event_key`),
  KEY `idx_p_quota_entry_1` (`account_id`, `quota_type`, `created_at`),
  KEY `idx_p_quota_entry_fk_reservation_id` (`reservation_id`),
  CONSTRAINT `fk_p_quota_entry_reservation_id` FOREIGN KEY (`reservation_id`) REFERENCES `p_quota_reservation` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_p_quota_entry_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_quota_entry_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_quota_entry_quota_type` CHECK (`quota_type` IN ('AVATAR_COUNT', 'TTS_CHAR', 'STORAGE_BYTE')),
  CONSTRAINT `ck_p_quota_entry_reservation_id` CHECK (`reservation_id` > 0),
  CONSTRAINT `ck_p_quota_entry_entry_type` CHECK (`entry_type` IN ('GRANT', 'RESERVE', 'SETTLE', 'RELEASE', 'STORAGE_FREE', 'ADJUST')),
  CONSTRAINT `ck_p_quota_entry_operator_id` CHECK (`operator_id` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='额度不可变流水';

-- 额度与用量 / 调用用量及厂商成本
CREATE TABLE IF NOT EXISTS `p_call_record` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '归属账号',
  `application_id` bigint NULL COMMENT '关联应用',
  `session_id` bigint NULL COMMENT '跨库定位标识，不参与外键',
  `turn_id` bigint NULL COMMENT '跨库轮次定位',
  `operation_key` varchar(128) NOT NULL COMMENT 'attempt或运行调用的全局业务标识',
  `capability` varchar(24) NOT NULL COMMENT 'GENERATION/LLM/ASR/TTS/TOOL/CONTEXT',
  `billing_owner` varchar(16) NOT NULL COMMENT 'PLATFORM/DEVELOPER/NONE',
  `provider_code` varchar(64) NULL COMMENT '厂商或转接标识',
  `model_id` varchar(128) NULL COMMENT '模型',
  `provider_request_id` varchar(128) NULL COMMENT '上游请求ID',
  `status` varchar(24) NOT NULL COMMENT 'STARTED/SUCCEEDED/FAILED/UNKNOWN/CANCELLED',
  `input_tokens` bigint NULL COMMENT '未提供为NULL',
  `output_tokens` bigint NULL COMMENT '未提供为NULL',
  `input_chars` bigint NULL COMMENT '输入字符数',
  `audio_duration_ms` bigint NULL COMMENT '音频时长',
  `image_count` int NULL COMMENT '图片数',
  `usage_available` tinyint NOT NULL DEFAULT 0 COMMENT '默认0',
  `cost_amount` decimal(18,6) NULL COMMENT '厂商成本；未知为NULL',
  `currency` char(3) NULL COMMENT '例如CNY',
  `cost_source` varchar(20) NOT NULL COMMENT 'UNKNOWN/PROVIDER/CONSOLE/ESTIMATED',
  `latency_ms` bigint NULL COMMENT '总耗时',
  `first_byte_ms` bigint NULL COMMENT '首字/首包耗时，按capability解释',
  `error_code` varchar(64) NULL COMMENT '安全错误码',
  `finished_at` datetime(3) NULL COMMENT '完成时间',
  `expires_at` datetime(3) NULL COMMENT '最终完成30天后清理',
  `quota_reservation_id` bigint NULL COMMENT '官方生成/语音预占ID；Session删除后仍可核对结算',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_call_record_1` (`operation_key`),
  KEY `idx_p_call_record_1` (`account_id`, `created_at`),
  KEY `idx_p_call_record_2` (`account_id`, `application_id`, `created_at`),
  KEY `idx_p_call_record_3` (`status`, `created_at`),
  KEY `idx_p_call_record_4` (`expires_at`),
  CONSTRAINT `ck_p_call_record_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_call_record_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_call_record_application_id` CHECK (`application_id` > 0),
  CONSTRAINT `ck_p_call_record_session_id` CHECK (`session_id` > 0),
  CONSTRAINT `ck_p_call_record_turn_id` CHECK (`turn_id` > 0),
  CONSTRAINT `ck_p_call_record_capability` CHECK (`capability` IN ('GENERATION', 'LLM', 'ASR', 'TTS', 'TOOL', 'CONTEXT')),
  CONSTRAINT `ck_p_call_record_billing_owner` CHECK (`billing_owner` IN ('PLATFORM', 'DEVELOPER', 'NONE')),
  CONSTRAINT `ck_p_call_record_status` CHECK (`status` IN ('STARTED', 'SUCCEEDED', 'FAILED', 'UNKNOWN', 'CANCELLED')),
  CONSTRAINT `ck_p_call_record_input_tokens` CHECK (`input_tokens` >= 0),
  CONSTRAINT `ck_p_call_record_output_tokens` CHECK (`output_tokens` >= 0),
  CONSTRAINT `ck_p_call_record_input_chars` CHECK (`input_chars` >= 0),
  CONSTRAINT `ck_p_call_record_audio_duration_ms` CHECK (`audio_duration_ms` >= 0),
  CONSTRAINT `ck_p_call_record_image_count` CHECK (`image_count` >= 0),
  CONSTRAINT `ck_p_call_record_usage_available` CHECK (`usage_available` IN (0, 1)),
  CONSTRAINT `ck_p_call_record_cost_amount` CHECK (`cost_amount` >= 0),
  CONSTRAINT `ck_p_call_record_cost_source` CHECK (`cost_source` IN ('UNKNOWN', 'PROVIDER', 'CONSOLE', 'ESTIMATED')),
  CONSTRAINT `ck_p_call_record_latency_ms` CHECK (`latency_ms` >= 0),
  CONSTRAINT `ck_p_call_record_first_byte_ms` CHECK (`first_byte_ms` >= 0),
  CONSTRAINT `ck_p_call_record_quota_reservation_id` CHECK (`quota_reservation_id` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='调用用量及厂商成本';

-- 额度与用量 / 每日汇总用量
CREATE TABLE IF NOT EXISTS `p_usage_daily` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '归属账号',
  `application_scope_id` bigint NOT NULL COMMENT '应用ID，无应用调用用0，避免NULL唯一键漏洞',
  `usage_date` date NOT NULL COMMENT 'UTC统计日，界面可换时区',
  `capability` varchar(24) NOT NULL COMMENT '能力类别',
  `billing_owner` varchar(16) NOT NULL COMMENT 'PLATFORM/DEVELOPER/NONE',
  `request_count` bigint NOT NULL DEFAULT 0 COMMENT '默认0',
  `success_count` bigint NOT NULL DEFAULT 0 COMMENT '默认0',
  `failure_count` bigint NOT NULL DEFAULT 0 COMMENT '默认0',
  `unknown_count` bigint NOT NULL DEFAULT 0 COMMENT '默认0',
  `input_tokens` bigint NOT NULL DEFAULT 0 COMMENT '默认0；仅已报告数值累计',
  `output_tokens` bigint NOT NULL DEFAULT 0 COMMENT '默认0',
  `input_chars` bigint NOT NULL DEFAULT 0 COMMENT '默认0',
  `image_count` bigint NOT NULL DEFAULT 0 COMMENT '默认0',
  `audio_duration_ms` bigint NOT NULL DEFAULT 0 COMMENT '默认0',
  `known_usage_count` bigint NOT NULL DEFAULT 0 COMMENT '默认0；避免缺失被误读为0',
  `known_cost_count` bigint NOT NULL DEFAULT 0 COMMENT '默认0',
  `cost_amount` decimal(18,6) NOT NULL DEFAULT 0 COMMENT '默认0；只汇总同币种已知成本',
  `currency` varchar(8) NOT NULL COMMENT 'CNY等；未知用UNKNOWN',
  `expires_at` datetime(3) NOT NULL COMMENT '统计日后12个月',
  `cancelled_count` bigint NOT NULL DEFAULT 0 COMMENT '默认0；取消调用数',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_usage_daily_1` (`account_id`, `application_scope_id`, `usage_date`, `capability`, `billing_owner`, `currency`),
  KEY `idx_p_usage_daily_1` (`account_id`, `usage_date`),
  KEY `idx_p_usage_daily_2` (`expires_at`),
  CONSTRAINT `ck_p_usage_daily_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_usage_daily_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_usage_daily_application_scope_id` CHECK (`application_scope_id` >= 0),
  CONSTRAINT `ck_p_usage_daily_capability` CHECK (`capability` IN ('GENERATION', 'LLM', 'ASR', 'TTS', 'TOOL', 'CONTEXT')),
  CONSTRAINT `ck_p_usage_daily_billing_owner` CHECK (`billing_owner` IN ('PLATFORM', 'DEVELOPER', 'NONE')),
  CONSTRAINT `ck_p_usage_daily_request_count` CHECK (`request_count` >= 0),
  CONSTRAINT `ck_p_usage_daily_success_count` CHECK (`success_count` >= 0),
  CONSTRAINT `ck_p_usage_daily_failure_count` CHECK (`failure_count` >= 0),
  CONSTRAINT `ck_p_usage_daily_unknown_count` CHECK (`unknown_count` >= 0),
  CONSTRAINT `ck_p_usage_daily_input_tokens` CHECK (`input_tokens` >= 0),
  CONSTRAINT `ck_p_usage_daily_output_tokens` CHECK (`output_tokens` >= 0),
  CONSTRAINT `ck_p_usage_daily_input_chars` CHECK (`input_chars` >= 0),
  CONSTRAINT `ck_p_usage_daily_image_count` CHECK (`image_count` >= 0),
  CONSTRAINT `ck_p_usage_daily_audio_duration_ms` CHECK (`audio_duration_ms` >= 0),
  CONSTRAINT `ck_p_usage_daily_known_usage_count` CHECK (`known_usage_count` >= 0),
  CONSTRAINT `ck_p_usage_daily_known_cost_count` CHECK (`known_cost_count` >= 0),
  CONSTRAINT `ck_p_usage_daily_cost_amount` CHECK (`cost_amount` >= 0),
  CONSTRAINT `ck_p_usage_daily_cancelled_count` CHECK (`cancelled_count` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='每日汇总用量';

-- 通知与可靠性 / 账号生成通知配置
CREATE TABLE IF NOT EXISTS `p_webhook_endpoint` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属开发者',
  `name` varchar(100) COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '显示名称',
  `url` varchar(2048) NOT NULL COMMENT 'HTTPS回调地址',
  `sign_secret_id` bigint NOT NULL COMMENT 'p_secret.id；签名秘密引用',
  `signature_version` varchar(32) NOT NULL COMMENT '验签协议版本',
  `status` varchar(20) NOT NULL COMMENT 'ACTIVE/DISABLED/DELETED',
  `events` json NOT NULL COMMENT '仅AVATAR_SUCCEEDED/AVATAR_FAILED',
  `timeout_ms` int NOT NULL COMMENT '投递超时',
  `max_attempts` int NOT NULL COMMENT '有限次重试上限',
  `revision` bigint NOT NULL DEFAULT 1 COMMENT '默认1；配置修订',
  PRIMARY KEY (`id`),
  KEY `idx_p_webhook_endpoint_1` (`account_id`, `status`),
  CONSTRAINT `ck_p_webhook_endpoint_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_webhook_endpoint_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_webhook_endpoint_sign_secret_id` CHECK (`sign_secret_id` > 0),
  CONSTRAINT `ck_p_webhook_endpoint_status` CHECK (`status` IN ('ACTIVE', 'DISABLED', 'DELETED')),
  CONSTRAINT `ck_p_webhook_endpoint_timeout_ms` CHECK (`timeout_ms` > 0),
  CONSTRAINT `ck_p_webhook_endpoint_max_attempts` CHECK (`max_attempts` > 0),
  CONSTRAINT `ck_p_webhook_endpoint_revision` CHECK (`revision` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='账号生成通知配置';

-- 通知与可靠性 / 事件及投递状态
CREATE TABLE IF NOT EXISTS `p_webhook_delivery` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属开发者',
  `endpoint_id` bigint NOT NULL COMMENT 'p_webhook_endpoint.id',
  `event_id` varchar(64) NOT NULL COMMENT '唯一外部事件ID，重试不变',
  `task_id` bigint NOT NULL COMMENT '任务ID，清理后可保留标识',
  `avatar_id` bigint NOT NULL COMMENT 'Avatar标识',
  `event_type` varchar(24) NOT NULL COMMENT 'AVATAR_SUCCEEDED/AVATAR_FAILED',
  `payload` json NOT NULL COMMENT '白名单事件字段，无素材和凭证',
  `endpoint_snapshot` json NOT NULL COMMENT '非秘密目标/协议/限制快照',
  `status` varchar(20) NOT NULL COMMENT 'PENDING/SENDING/DELIVERED/EXHAUSTED/CANCELLED',
  `attempt_count` int NOT NULL DEFAULT 0 COMMENT '默认0',
  `last_http_status` int NULL COMMENT '最近HTTP状态',
  `last_error_code` varchar(64) NULL COMMENT '脱敏错误，不存完整响应',
  `next_attempt_at` datetime(3) NULL COMMENT '重试时间',
  `lease_owner` varchar(128) NULL COMMENT '投递者',
  `lease_expires_at` datetime(3) NULL COMMENT '投递租约',
  `delivered_at` datetime(3) NULL COMMENT '成功时间',
  `expires_at` datetime(3) NULL COMMENT '终态后30天',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_webhook_delivery_1` (`event_id`, `endpoint_id`),
  KEY `idx_p_webhook_delivery_1` (`status`, `next_attempt_at`),
  KEY `idx_p_webhook_delivery_2` (`status`, `lease_expires_at`),
  KEY `idx_p_webhook_delivery_3` (`account_id`, `created_at`),
  KEY `idx_p_webhook_delivery_4` (`expires_at`),
  CONSTRAINT `ck_p_webhook_delivery_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_webhook_delivery_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_webhook_delivery_endpoint_id` CHECK (`endpoint_id` > 0),
  CONSTRAINT `ck_p_webhook_delivery_task_id` CHECK (`task_id` > 0),
  CONSTRAINT `ck_p_webhook_delivery_avatar_id` CHECK (`avatar_id` > 0),
  CONSTRAINT `ck_p_webhook_delivery_event_type` CHECK (`event_type` IN ('AVATAR_SUCCEEDED', 'AVATAR_FAILED')),
  CONSTRAINT `ck_p_webhook_delivery_status` CHECK (`status` IN ('PENDING', 'SENDING', 'DELIVERED', 'EXHAUSTED', 'CANCELLED')),
  CONSTRAINT `ck_p_webhook_delivery_attempt_count` CHECK (`attempt_count` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='事件及投递状态';

-- 通知与可靠性 / Webhook逐次投递记录
CREATE TABLE IF NOT EXISTS `p_webhook_attempt` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属账号',
  `delivery_id` bigint NOT NULL COMMENT 'p_webhook_delivery.id',
  `attempt_no` int NOT NULL COMMENT '从1递增',
  `started_at` datetime(3) NOT NULL COMMENT '发出时间',
  `finished_at` datetime(3) NULL COMMENT '完成时间',
  `http_status` int NULL COMMENT 'HTTP状态',
  `error_code` varchar(64) NULL COMMENT '安全错误码',
  `latency_ms` bigint NULL COMMENT '耗时',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_webhook_attempt_1` (`delivery_id`, `attempt_no`),
  KEY `idx_p_webhook_attempt_1` (`account_id`, `created_at`),
  CONSTRAINT `ck_p_webhook_attempt_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_webhook_attempt_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_webhook_attempt_delivery_id` CHECK (`delivery_id` > 0),
  CONSTRAINT `ck_p_webhook_attempt_attempt_no` CHECK (`attempt_no` > 0),
  CONSTRAINT `ck_p_webhook_attempt_latency_ms` CHECK (`latency_ms` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='Webhook逐次投递记录';

-- 通知与可靠性 / 管理API幂等结果
CREATE TABLE IF NOT EXISTS `p_api_idempotency` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属账号',
  `scope` varchar(64) NOT NULL COMMENT '操作、目标及必要身份的规范对象SHA-256小写十六进制，固定64字符',
  `request_id` varchar(64) NOT NULL COMMENT '后端传入幂等请求ID',
  `request_hash` binary(32) NOT NULL COMMENT '规范化业务参数SHA-256；秘密字段先做服务端keyed digest，不存正文',
  `resource_type` varchar(32) NULL COMMENT '创建资源类型',
  `resource_id` bigint NULL COMMENT '已创建资源ID',
  `status` varchar(20) NOT NULL COMMENT 'PROCESSING/SUCCEEDED/FAILED',
  `error_code` varchar(64) NULL COMMENT '安全错误',
  `expires_at` datetime(3) NOT NULL COMMENT '至少保留24小时并覆盖执行/补偿期；未完成不删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_api_idempotency_1` (`account_id`, `scope`, `request_id`),
  KEY `idx_p_api_idempotency_1` (`expires_at`),
  CONSTRAINT `ck_p_api_idempotency_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_api_idempotency_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_api_idempotency_resource_id` CHECK (`resource_id` > 0),
  CONSTRAINT `ck_p_api_idempotency_status` CHECK (`status` IN ('PROCESSING', 'SUCCEEDED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='管理API幂等结果';

-- 可靠性基础表 / 本地事务事件发件箱
CREATE TABLE IF NOT EXISTS `p_outbox` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '业务归属账号；纯系统事件使用操作管理员账号',
  `event_id` varchar(64) NOT NULL COMMENT '全局事件ID',
  `event_type` varchar(64) NOT NULL COMMENT '业务事件类型',
  `aggregate_type` varchar(32) NOT NULL COMMENT '聚合实体类型',
  `aggregate_id` varchar(64) NOT NULL COMMENT '实体ID',
  `schema_version` int NOT NULL COMMENT '消息协议版本',
  `trace_id` varchar(64) NOT NULL COMMENT '追踪ID',
  `payload` json NOT NULL COMMENT '白名单标识、状态与必要用量，不含秘密/正文/素材',
  `status` varchar(20) NOT NULL COMMENT 'PENDING/SENDING/SENT',
  `attempt_count` int NOT NULL DEFAULT 0 COMMENT '默认0',
  `next_run_at` datetime(3) NULL COMMENT '发送时间',
  `lease_owner` varchar(128) NULL COMMENT '发送者',
  `lease_expires_at` datetime(3) NULL COMMENT '租约',
  `published_at` datetime(3) NULL COMMENT '发布确认时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_outbox_1` (`event_id`),
  KEY `idx_p_outbox_1` (`status`, `next_run_at`),
  KEY `idx_p_outbox_2` (`status`, `lease_expires_at`),
  CONSTRAINT `ck_p_outbox_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_outbox_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_p_outbox_schema_version` CHECK (`schema_version` > 0),
  CONSTRAINT `ck_p_outbox_status` CHECK (`status` IN ('PENDING', 'SENDING', 'SENT')),
  CONSTRAINT `ck_p_outbox_attempt_count` CHECK (`attempt_count` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='本地事务事件发件箱';

-- 可靠性基础表 / 消费事件去重
CREATE TABLE IF NOT EXISTS `p_inbox` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '事件归属账号',
  `consumer_name` varchar(64) NOT NULL COMMENT '消费逻辑标识',
  `event_id` varchar(64) NOT NULL COMMENT '上游事件ID',
  `payload_hash` binary(32) NOT NULL COMMENT '防止同事件ID不同内容',
  `processed_at` datetime(3) NOT NULL COMMENT '本地业务事务完成时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_inbox_1` (`consumer_name`, `event_id`),
  KEY `idx_p_inbox_1` (`processed_at`),
  CONSTRAINT `ck_p_inbox_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_inbox_account_id` CHECK (`account_id` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='消费事件去重';

-- 可靠性基础表 / 持久扫描任务租约
CREATE TABLE IF NOT EXISTS `p_job_lease` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `job_key` varchar(100) NOT NULL COMMENT '清理/投递/补偿扫描任务标识',
  `lease_owner` varchar(128) NULL COMMENT '当前执行实例',
  `lease_epoch` bigint NOT NULL DEFAULT 0 COMMENT '默认0；领取代数',
  `lease_expires_at` datetime(3) NULL COMMENT '租约到期',
  `last_completed_at` datetime(3) NULL COMMENT '上次完成',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_p_job_lease_1` (`job_key`),
  KEY `idx_p_job_lease_1` (`lease_expires_at`),
  CONSTRAINT `ck_p_job_lease_id` CHECK (`id` > 0),
  CONSTRAINT `ck_p_job_lease_lease_epoch` CHECK (`lease_epoch` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='持久扫描任务租约';


-- Local development administrator and permissions seed. Flyway executes V1 once; UPSERTs make this seed harmless if applied manually to an equivalent empty schema.
INSERT INTO sys_user
    (user_id, dept_id, user_name, nick_name, user_type, email, email_normalized,
     email_verified_at, auth_epoch, avatar_file_id, phonenumber, sex, avatar,
     password, status, del_flag, login_ip, login_date, pwd_update_date,
     create_by, create_time, update_by, update_time, remark)
VALUES
    (1, NULL, 'admin', '平台管理员', '00', 'admin@local.invalid', 'admin@local.invalid',
     NOW(3), 1, NULL, '', '2', '',
     '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2',
     '0', '0', '', NULL, NOW(), 'bootstrap', NOW(), '', NULL, '本地开发初始管理员')
ON DUPLICATE KEY UPDATE user_id = user_id;

INSERT INTO sys_role
    (role_id, role_name, role_key, role_sort, data_scope, menu_check_strictly,
     dept_check_strictly, status, del_flag, create_by, create_time, update_by, update_time, remark)
VALUES
    (1, '超级管理员', 'admin', 1, '1', 1, 1, '0', '0', 'bootstrap', NOW(), '', NULL, '本地开发超级管理员')
ON DUPLICATE KEY UPDATE role_id = role_id;

INSERT INTO sys_menu
    (menu_id, menu_name, parent_id, order_num, path, component, `query`, route_name,
     is_frame, is_cache, menu_type, visible, status, perms, icon,
     create_by, create_time, update_by, update_time, remark)
VALUES
    (1,    '系统管理', 0,   1, 'system',    NULL,                  '', '',          1, 0, 'M', '0', '0', '',                    'system',      'bootstrap', NOW(), '', NULL, '系统管理目录'),
    (100,  '用户管理', 1,   1, 'user',      'system/user/index',   '', '',          1, 0, 'C', '0', '0', 'system:user:list',    'user',        'bootstrap', NOW(), '', NULL, '用户管理'),
    (101,  '角色管理', 1,   2, 'role',      'system/role/index',   '', '',          1, 0, 'C', '0', '0', 'system:role:list',    'peoples',     'bootstrap', NOW(), '', NULL, '角色管理'),
    (102,  '菜单管理', 1,   3, 'menu',      'system/menu/index',   '', '',          1, 0, 'C', '0', '0', 'system:menu:list',    'tree-table',  'bootstrap', NOW(), '', NULL, '菜单管理'),
    (108,  '日志管理', 1,   4, 'log',       '',                    '', '',          1, 0, 'M', '0', '0', '',                    'log',         'bootstrap', NOW(), '', NULL, '日志管理目录'),
    (500,  '操作日志', 108, 1, 'operlog',   'system/operlog/index','', '',          1, 0, 'C', '0', '0', 'system:operlog:list', 'form',        'bootstrap', NOW(), '', NULL, '操作日志'),
    (501,  '登录日志', 108, 2, 'logininfor','system/logininfor/index','', '',        1, 0, 'C', '0', '0', 'system:logininfor:list','logininfor', 'bootstrap', NOW(), '', NULL, '登录日志'),
    (1000, '用户查询', 100, 1, '',          '',                    '', '',          1, 0, 'F', '0', '0', 'system:user:query',   '#',           'bootstrap', NOW(), '', NULL, ''),
    (1001, '用户新增', 100, 2, '',          '',                    '', '',          1, 0, 'F', '0', '0', 'system:user:add',     '#',           'bootstrap', NOW(), '', NULL, ''),
    (1002, '用户修改', 100, 3, '',          '',                    '', '',          1, 0, 'F', '0', '0', 'system:user:edit',    '#',           'bootstrap', NOW(), '', NULL, ''),
    (1003, '用户删除', 100, 4, '',          '',                    '', '',          1, 0, 'F', '0', '0', 'system:user:remove',  '#',           'bootstrap', NOW(), '', NULL, '')
ON DUPLICATE KEY UPDATE menu_id = menu_id;

INSERT INTO sys_user_role (user_id, role_id)
VALUES (1, 1)
ON DUPLICATE KEY UPDATE user_id = user_id;

INSERT INTO sys_role_menu (role_id, menu_id)
VALUES
    (1, 1), (1, 100), (1, 101), (1, 102), (1, 108), (1, 500), (1, 501),
    (1, 1000), (1, 1001), (1, 1002), (1, 1003)
ON DUPLICATE KEY UPDATE role_id = role_id;
