spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lowerCaseServiceId: true
              enabled: false
          routes:
          - id: ruoyi-auth
            uri: lb://ruoyi-auth
            predicates:
            - Path=/auth/**
            filters:
            - name: CacheRequestBody
              args:
                bodyClass: java.lang.String
            - ValidateCodeFilter
            - StripPrefix=1
          - id: ruoyi-job
            uri: lb://ruoyi-job
            predicates:
            - Path=/schedule/**
            filters:
            - StripPrefix=1
          - id: ruoyi-system
            uri: lb://ruoyi-system
            predicates:
            - Path=/system/**
            filters:
            - StripPrefix=1
          - id: platform-official-voices
            uri: lb://ruoyi-system
            predicates:
            - Path=/api/v1/voices/**,/api/v1/applications/**,/api/v1/developer/**,/api/v1/admin/applications/**,/api/v1/admin/voices/**,/api/v1/admin/avatars/**,/api/v1/admin/official-services/**
          - id: developer-management
            uri: lb://ruoyi-system
            predicates:
            - Path=/openapi/v1/management/**
          - id: developer-sessions
            uri: lb://ruoyi-session
            predicates:
            - Path=/openapi/v1/sessions/**
          - id: platform-debug-system
            uri: lb://ruoyi-system
            predicates:
            - Path=/api/v1/debug-sessions/**
          - id: platform-runtime
            uri: lb://ruoyi-session
            predicates:
            - Path=/api/v1/runtime/**
          - id: platform-realtime
            uri: lb:ws://ruoyi-session
            predicates:
            - Path=/api/v1/realtime
          - id: ruoyi-gen
            uri: lb://ruoyi-gen
            predicates:
            - Path=/code/**
            filters:
            - StripPrefix=1
security:
  captcha:
    enabled: true
    type: math
  xss:
    enabled: true
    excludeUrls: []
  ignore:
    whites:
    - /auth/logout
    - /auth/login
    - /auth/register
    - /auth/register/code
    - /*/v2/api-docs
    - /*/v3/api-docs
    - /csrf
springdoc:
  webjars:
    prefix: null
  swagger-ui:
    urls:
    - name: ruoyi-job
      url: /schedule/v3/api-docs
    - name: ruoyi-system
      url: /system/v3/api-docs
    - name: ruoyi-gen
      url: /code/v3/api-docs
