<template>
  <div class="app-container">
    <el-alert title="核对只查询已有厂商任务或记录人工依据，不会发起新的生成或把未完成产物标为已发布。成本为空表示未知，不是零。" type="warning" :closable="false" class="mb16" />
    <el-tabs v-model="tab" @tab-change="reload"><el-tab-pane label="制作任务" name="tasks" /><el-tab-pane label="调用事实" name="calls" /></el-tabs>
    <el-form inline><el-form-item label="账号"><el-input v-model="filters.accountId" clearable /></el-form-item><el-form-item label="状态"><el-select v-model="filters.status" clearable><el-option v-for="status in statuses" :key="status" :label="status" :value="status" /></el-select></el-form-item><el-form-item><el-button type="primary" @click="reload">查询</el-button></el-form-item></el-form>
    <el-table v-if="tab === 'tasks'" :data="tasks" v-loading="loading" border><el-table-column prop="taskId" label="任务" min-width="150" /><el-table-column prop="accountId" label="账号" width="140" /><el-table-column prop="status" label="状态" width="120" /><el-table-column prop="progress" label="进度" width="90" /><el-table-column prop="errorCode" label="安全错误" min-width="160" /><el-table-column label="操作" width="100"><template #default="{ row }"><el-button link @click="detail(row)">详情/核对</el-button></template></el-table-column></el-table>
    <el-table v-else :data="calls" v-loading="loading" border><el-table-column prop="callId" label="调用" min-width="140" /><el-table-column prop="operationKey" label="操作标识" min-width="220" /><el-table-column prop="capability" label="能力" width="110" /><el-table-column prop="status" label="状态" width="110" /><el-table-column label="成本" width="160"><template #default="{ row }">{{ row.costAmount == null ? '未知' : `${row.costAmount} ${row.currency || ''}` }}</template></el-table-column><el-table-column prop="errorCode" label="安全错误" min-width="160" /><el-table-column label="操作" width="100"><template #default="{ row }"><el-button link :disabled="row.status !== 'UNKNOWN'" @click="review(row)">{{ row.status === 'UNKNOWN' ? '人工核对' : '已定案' }}</el-button></template></el-table-column></el-table>
    <el-dialog v-model="detailOpen" title="任务尝试" width="850px"><el-table :data="attempts" border><el-table-column prop="attemptId" label="尝试" /><el-table-column prop="status" label="状态" /><el-table-column prop="providerRequestId" label="厂商请求" /><el-table-column prop="providerTaskId" label="厂商任务" /><el-table-column prop="errorCode" label="安全错误" /><el-table-column label="操作"><template #default="{ row }"><el-button link :disabled="!row.allowedOperations.includes('reconcile')" @click="reconcile(row)">核对原结果</el-button></template></el-table-column></el-table></el-dialog>
    <el-dialog v-model="reviewOpen" title="人工核对调用事实" width="520px"><el-form label-width="100px"><el-form-item label="确认终态"><el-select v-model="reviewForm.reviewedStatus"><el-option label="成功" value="SUCCEEDED" /><el-option label="失败" value="FAILED" /><el-option label="已取消" value="CANCELLED" /></el-select></el-form-item><el-form-item label="安全依据"><el-input v-model="reviewForm.evidenceNote" type="textarea" :rows="4" maxlength="1000" show-word-limit /></el-form-item><el-form-item label="成本"><el-input v-model="reviewForm.costAmount" placeholder="未知则留空" /></el-form-item><el-form-item label="币种"><el-input v-model="reviewForm.currency" maxlength="3" placeholder="例如 CNY" /></el-form-item><el-form-item label="成本来源"><el-select v-model="reviewForm.costSource"><el-option label="控制台依据" value="CONSOLE" /><el-option label="估算" value="ESTIMATED" /></el-select></el-form-item></el-form><template #footer><el-button @click="reviewOpen = false">取消</el-button><el-button type="primary" @click="submitReview">保存核对</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts" name="PlatformOperations">
import { getTask, listCalls, listTasks, reconcileAttempt, reviewCall, type Attempt, type CallRecord, type GenerationTask } from '@/api/operations'
const { proxy } = getCurrentInstance(); const tab = ref<'tasks' | 'calls'>('tasks'); const loading = ref(false); const tasks = ref<GenerationTask[]>([]); const calls = ref<CallRecord[]>([]); const attempts = ref<Attempt[]>([]); const activeTask = ref<GenerationTask>(); const detailOpen = ref(false); const reviewOpen = ref(false); const activeCall = ref<CallRecord>(); const reviewForm = reactive({ reviewedStatus: 'FAILED', evidenceNote: '', costAmount: '', currency: '', costSource: 'CONSOLE' }); const filters = reactive({ accountId: '', status: '' }); const statuses = ['QUEUED', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'STARTED', 'UNKNOWN', 'CANCELLED']
function reload() { loading.value = true; const params = { ...filters, pageNum: 1, pageSize: 100 }; const source = tab.value === 'tasks' ? listTasks(params) : listCalls(params); source.then((r: any) => { if (tab.value === 'tasks') tasks.value = r.data?.items || []; else calls.value = r.data?.items || [] }).finally(() => loading.value = false) }
function detail(task: GenerationTask) { activeTask.value = task; getTask(task.taskId).then(r => { attempts.value = r.data?.attempts || []; detailOpen.value = true }) }
function reconcile(attempt: Attempt) { if (!activeTask.value) return; proxy?.$modal.prompt('请输入安全核对原因（不会重新生成）：', '核对原厂商结果').then(({ value }: { value: string }) => reconcileAttempt(activeTask.value!.taskId, attempt, value?.trim())).then(() => { proxy?.$modal.msgSuccess('已安排原任务核对。'); detail(activeTask.value!) }).catch(() => {}) }
function review(call: CallRecord) { activeCall.value = call; reviewForm.reviewedStatus = 'FAILED'; reviewForm.evidenceNote = ''; reviewForm.costAmount = ''; reviewForm.currency = ''; reviewForm.costSource = 'CONSOLE'; reviewOpen.value = true }
function submitReview() { if (!activeCall.value || !reviewForm.evidenceNote.trim()) return proxy?.$modal.msgWarning('请填写安全核对依据。'); reviewCall(activeCall.value, { reviewedStatus: reviewForm.reviewedStatus, evidenceNote: reviewForm.evidenceNote.trim(), costAmount: reviewForm.costAmount || undefined, currency: reviewForm.currency.trim().toUpperCase() || undefined, costSource: reviewForm.costSource }).then(() => { reviewOpen.value = false; proxy?.$modal.msgSuccess('调用事实已核对。'); reload() }) }
onMounted(reload)
</script>
<style scoped>.mb16 { margin-bottom: 16px; }</style>
