-- M1 baseline migrated from RuoYi-Cloud/sql/init-platform-and-session.sql session_db section.
-- The source one-shot SQL remains for existing local setup only; this versioned migration is authoritative for new empty session_db instances.


-- 13 session business tables; platform identifiers are logical references.
-- 会话身份 / 应用业务身份与持久撤销版本
CREATE TABLE IF NOT EXISTS `s_principal` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '开发者账号，跨库引用sys_user',
  `application_id` bigint NOT NULL COMMENT '平台应用ID',
  `principal_type` varchar(16) NOT NULL COMMENT 'BUSINESS/DEBUG',
  `external_user_id` varchar(191) NOT NULL COMMENT '开发者后端验证的稳定用户ID；区分大小写',
  `status` varchar(20) NOT NULL COMMENT 'ACTIVE/DISABLED',
  `auth_epoch` bigint NOT NULL DEFAULT 1 COMMENT '默认1；退出/撤销全部会话授权递增',
  `last_seen_at` datetime(3) NOT NULL COMMENT '最近业务活动',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_principal_1` (`account_id`, `application_id`, `principal_type`, `external_user_id`),
  KEY `idx_s_principal_1` (`account_id`, `application_id`, `status`),
  CONSTRAINT `ck_s_principal_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_principal_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_s_principal_application_id` CHECK (`application_id` > 0),
  CONSTRAINT `ck_s_principal_principal_type` CHECK (`principal_type` IN ('BUSINESS', 'DEBUG')),
  CONSTRAINT `ck_s_principal_status` CHECK (`status` IN ('ACTIVE', 'DISABLED')),
  CONSTRAINT `ck_s_principal_auth_epoch` CHECK (`auth_epoch` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='应用业务身份与持久撤销版本';

-- 会话身份 / 会话归属与恢复
CREATE TABLE IF NOT EXISTS `s_session` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '开发者账号',
  `application_id` bigint NOT NULL COMMENT '应用',
  `principal_id` bigint NOT NULL COMMENT 's_principal.id',
  `app_config_id` bigint NOT NULL COMMENT '固定平台配置版本，跨库逻辑引用',
  `create_request_id` varchar(64) NOT NULL COMMENT '新建会话幂等键',
  `reference_operation_id` varchar(64) NOT NULL COMMENT '平台引用预留操作ID',
  `status` varchar(20) NOT NULL COMMENT 'CREATING/ACTIVE/DELETING/DELETED/FAILED',
  `auth_epoch` bigint NOT NULL DEFAULT 1 COMMENT '默认1；仅撤销本Session时递增',
  `connection_epoch` bigint NOT NULL DEFAULT 0 COMMENT '默认0；持久连接代数',
  `active_turn_id` bigint NULL COMMENT '当前轮次，同库逻辑关联',
  `next_turn_no` bigint NOT NULL DEFAULT 1 COMMENT '默认1',
  `next_message_seq` bigint NOT NULL DEFAULT 1 COMMENT '默认1',
  `last_activity_at` datetime(3) NOT NULL COMMENT '成功用户请求/业务Context更新；心跳不续期',
  `expires_at` datetime(3) NOT NULL COMMENT '最后活动时间加30天',
  `deleted_at` datetime(3) NULL COMMENT '逻辑不可恢复时间',
  `revision` bigint NOT NULL DEFAULT 1 COMMENT '默认1；状态/连接/轮次并发控制',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_session_1` (`account_id`, `application_id`, `principal_id`, `create_request_id`),
  KEY `idx_s_session_1` (`account_id`, `application_id`, `principal_id`, `last_activity_at`),
  KEY `idx_s_session_2` (`status`, `expires_at`),
  KEY `idx_s_session_fk_principal_id` (`principal_id`),
  CONSTRAINT `fk_s_session_principal_id` FOREIGN KEY (`principal_id`) REFERENCES `s_principal` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_s_session_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_session_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_s_session_application_id` CHECK (`application_id` > 0),
  CONSTRAINT `ck_s_session_principal_id` CHECK (`principal_id` > 0),
  CONSTRAINT `ck_s_session_app_config_id` CHECK (`app_config_id` > 0),
  CONSTRAINT `ck_s_session_status` CHECK (`status` IN ('CREATING', 'ACTIVE', 'DELETING', 'DELETED', 'FAILED')),
  CONSTRAINT `ck_s_session_auth_epoch` CHECK (`auth_epoch` > 0),
  CONSTRAINT `ck_s_session_connection_epoch` CHECK (`connection_epoch` >= 0),
  CONSTRAINT `ck_s_session_active_turn_id` CHECK (`active_turn_id` > 0),
  CONSTRAINT `ck_s_session_next_turn_no` CHECK (`next_turn_no` > 0),
  CONSTRAINT `ck_s_session_next_message_seq` CHECK (`next_message_seq` > 0),
  CONSTRAINT `ck_s_session_revision` CHECK (`revision` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='会话归属与恢复';

-- 会话身份 / 短期Session授权
CREATE TABLE IF NOT EXISTS `s_session_grant` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '归属账号',
  `session_id` bigint NOT NULL COMMENT 's_session.id',
  `principal_id` bigint NOT NULL COMMENT 's_principal.id',
  `application_id` bigint NOT NULL COMMENT '应用ID',
  `grant_source` varchar(24) NOT NULL COMMENT 'BUSINESS_KEY/CONSOLE_DEBUG，须匹配Session的BUSINESS/DEBUG身份',
  `issuer_console_ref` binary(32) NULL COMMENT 'CONSOLE_DEBUG必填后台登录引用摘要；BUSINESS_KEY为空，不存后台Token',
  `issuer_key_id` bigint NULL COMMENT 'BUSINESS_KEY必填p_access_key.id；CONSOLE_DEBUG为空',
  `token_id` varchar(64) NOT NULL COMMENT 'Token唯一标识/JTI；不存完整Token',
  `scopes` json NOT NULL COMMENT '签发的S运行权限；运行时再受固定配置与当前授权限制',
  `account_epoch` bigint NOT NULL COMMENT '签发时账号版本',
  `application_epoch` bigint NOT NULL COMMENT '签发时应用版本',
  `principal_epoch` bigint NOT NULL COMMENT '签发时业务用户版本',
  `session_epoch` bigint NOT NULL COMMENT '签发时Session版本',
  `status` varchar(20) NOT NULL COMMENT 'ACTIVE/REVOKED',
  `expires_at` datetime(3) NOT NULL COMMENT '短期过期时间',
  `revoked_at` datetime(3) NULL COMMENT '撤销时间',
  `issuer_key_epoch` bigint NULL COMMENT 'BUSINESS_KEY必填签发Key的auth_epoch；CONSOLE_DEBUG为空',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_session_grant_1` (`token_id`),
  KEY `idx_s_session_grant_1` (`account_id`, `session_id`, `status`),
  KEY `idx_s_session_grant_2` (`expires_at`),
  KEY `idx_s_session_grant_3` (`issuer_key_id`, `status`),
  KEY `idx_s_session_grant_4` (`account_id`, `issuer_console_ref`, `status`),
  KEY `idx_s_session_grant_fk_session_id` (`session_id`),
  CONSTRAINT `fk_s_session_grant_session_id` FOREIGN KEY (`session_id`) REFERENCES `s_session` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_s_session_grant_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_session_grant_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_s_session_grant_session_id` CHECK (`session_id` > 0),
  CONSTRAINT `ck_s_session_grant_principal_id` CHECK (`principal_id` > 0),
  CONSTRAINT `ck_s_session_grant_application_id` CHECK (`application_id` > 0),
  CONSTRAINT `ck_s_session_grant_grant_source` CHECK (`grant_source` IN ('BUSINESS_KEY', 'CONSOLE_DEBUG')),
  CONSTRAINT `ck_s_session_grant_issuer_key_id` CHECK (`issuer_key_id` > 0),
  CONSTRAINT `ck_s_session_grant_account_epoch` CHECK (`account_epoch` > 0),
  CONSTRAINT `ck_s_session_grant_application_epoch` CHECK (`application_epoch` > 0),
  CONSTRAINT `ck_s_session_grant_principal_epoch` CHECK (`principal_epoch` > 0),
  CONSTRAINT `ck_s_session_grant_session_epoch` CHECK (`session_epoch` > 0),
  CONSTRAINT `ck_s_session_grant_status` CHECK (`status` IN ('ACTIVE', 'REVOKED')),
  CONSTRAINT `ck_s_session_grant_issuer_key_epoch` CHECK (`issuer_key_epoch` > 0),
  CONSTRAINT `ck_s_session_grant_issuer` CHECK ((`grant_source` = 'BUSINESS_KEY' AND `issuer_key_id` IS NOT NULL AND `issuer_key_epoch` IS NOT NULL AND `issuer_console_ref` IS NULL) OR (`grant_source` = 'CONSOLE_DEBUG' AND `issuer_console_ref` IS NOT NULL AND `issuer_key_id` IS NULL AND `issuer_key_epoch` IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='短期Session授权';

-- 消息与运行记录 / 会话轮次
CREATE TABLE IF NOT EXISTS `s_turn` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '归属账号',
  `session_id` bigint NOT NULL COMMENT '所属会话',
  `turn_no` bigint NOT NULL COMMENT '会话内递增',
  `client_request_id` varchar(64) NOT NULL COMMENT '本轮幂等ID',
  `request_hash` binary(32) NOT NULL COMMENT '请求摘要，不保存临时数据正文',
  `turn_type` varchar(16) NOT NULL COMMENT 'CHAT/SPEAK',
  `status` varchar(20) NOT NULL COMMENT 'RUNNING/COMPLETED/INTERRUPTED/FAILED',
  `text_status` varchar(20) NOT NULL COMMENT 'NOT_REQUESTED/RUNNING/COMPLETED/FAILED/INTERRUPTED；SPEAK为NOT_REQUESTED',
  `audio_status` varchar(20) NOT NULL COMMENT 'NOT_REQUESTED/RUNNING/COMPLETED/FAILED/INTERRUPTED/UNKNOWN；TTS合成状态',
  `playback_status` varchar(20) NOT NULL COMMENT 'NOT_REQUESTED/WAITING/PLAYING/COMPLETED/FAILED/STOPPED/UNKNOWN；播放观测',
  `connection_epoch` bigint NOT NULL COMMENT '接收请求时连接代数',
  `input_source` varchar(16) NOT NULL COMMENT 'TEXT/ASR/DEVELOPER',
  `include_in_history` tinyint NOT NULL DEFAULT 0 COMMENT 'CHAT为1，SPEAK默认0',
  `cancel_reason` varchar(32) NULL COMMENT 'USER_STOP/REPLACED/DISCONNECTED/REVOKED',
  `last_event_seq` bigint NOT NULL DEFAULT 0 COMMENT '默认0；运行事件编号',
  `started_at` datetime(3) NOT NULL COMMENT '开始时间',
  `ended_at` datetime(3) NULL COMMENT '结束时间',
  `error_code` varchar(64) NULL COMMENT '安全错误码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_turn_1` (`session_id`, `turn_no`),
  UNIQUE KEY `uq_s_turn_2` (`session_id`, `client_request_id`),
  KEY `idx_s_turn_1` (`account_id`, `session_id`, `created_at`),
  KEY `idx_s_turn_2` (`status`, `started_at`),
  CONSTRAINT `fk_s_turn_session_id` FOREIGN KEY (`session_id`) REFERENCES `s_session` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_s_turn_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_turn_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_s_turn_session_id` CHECK (`session_id` > 0),
  CONSTRAINT `ck_s_turn_turn_no` CHECK (`turn_no` > 0),
  CONSTRAINT `ck_s_turn_turn_type` CHECK (`turn_type` IN ('CHAT', 'SPEAK')),
  CONSTRAINT `ck_s_turn_status` CHECK (`status` IN ('RUNNING', 'COMPLETED', 'INTERRUPTED', 'FAILED')),
  CONSTRAINT `ck_s_turn_text_status` CHECK (`text_status` IN ('NOT_REQUESTED', 'RUNNING', 'COMPLETED', 'FAILED', 'INTERRUPTED')),
  CONSTRAINT `ck_s_turn_audio_status` CHECK (`audio_status` IN ('NOT_REQUESTED', 'RUNNING', 'COMPLETED', 'FAILED', 'INTERRUPTED', 'UNKNOWN')),
  CONSTRAINT `ck_s_turn_playback_status` CHECK (`playback_status` IN ('NOT_REQUESTED', 'WAITING', 'PLAYING', 'COMPLETED', 'FAILED', 'STOPPED', 'UNKNOWN')),
  CONSTRAINT `ck_s_turn_connection_epoch` CHECK (`connection_epoch` >= 0),
  CONSTRAINT `ck_s_turn_input_source` CHECK (`input_source` IN ('TEXT', 'ASR', 'DEVELOPER')),
  CONSTRAINT `ck_s_turn_include_in_history` CHECK (`include_in_history` IN (0, 1)),
  CONSTRAINT `ck_s_turn_cancel_reason` CHECK (`cancel_reason` IN ('USER_STOP', 'REPLACED', 'DISCONNECTED', 'REVOKED')),
  CONSTRAINT `ck_s_turn_last_event_seq` CHECK (`last_event_seq` >= 0),
  CONSTRAINT `ck_s_turn_history` CHECK (`turn_type` <> 'CHAT' OR `include_in_history` = 1),
  CONSTRAINT `ck_s_turn_speak_text` CHECK (`turn_type` <> 'SPEAK' OR `text_status` = 'NOT_REQUESTED')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='会话轮次';

-- 消息与运行记录 / 按条存储的对话文本
CREATE TABLE IF NOT EXISTS `s_message` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '归属账号',
  `session_id` bigint NOT NULL COMMENT '所属会话',
  `turn_id` bigint NOT NULL COMMENT '所属轮次',
  `message_seq` bigint NOT NULL COMMENT '会话内唯一递增',
  `role` varchar(16) NOT NULL COMMENT 'USER/ASSISTANT',
  `content` mediumtext NOT NULL COMMENT '对话文本，不含截图/工具原结果',
  `status` varchar(20) NOT NULL COMMENT 'STREAMING/COMPLETED/INTERRUPTED/FAILED',
  `input_source` varchar(16) NOT NULL COMMENT 'TEXT/ASR/LLM',
  `token_count` bigint NULL COMMENT '可获得时保存',
  `is_history` tinyint NOT NULL DEFAULT 1 COMMENT '默认1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_message_1` (`session_id`, `message_seq`),
  KEY `idx_s_message_1` (`account_id`, `session_id`, `message_seq`),
  KEY `idx_s_message_2` (`turn_id`),
  CONSTRAINT `fk_s_message_turn_id` FOREIGN KEY (`turn_id`) REFERENCES `s_turn` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_s_message_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_message_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_s_message_session_id` CHECK (`session_id` > 0),
  CONSTRAINT `ck_s_message_turn_id` CHECK (`turn_id` > 0),
  CONSTRAINT `ck_s_message_message_seq` CHECK (`message_seq` > 0),
  CONSTRAINT `ck_s_message_role` CHECK (`role` IN ('USER', 'ASSISTANT')),
  CONSTRAINT `ck_s_message_status` CHECK (`status` IN ('STREAMING', 'COMPLETED', 'INTERRUPTED', 'FAILED')),
  CONSTRAINT `ck_s_message_input_source` CHECK (`input_source` IN ('TEXT', 'ASR', 'LLM')),
  CONSTRAINT `ck_s_message_token_count` CHECK (`token_count` >= 0),
  CONSTRAINT `ck_s_message_is_history` CHECK (`is_history` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='按条存储的对话文本';

-- 消息与运行记录 / 后端维护的Session Context
CREATE TABLE IF NOT EXISTS `s_session_context` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '归属账号',
  `session_id` bigint NOT NULL COMMENT '所属会话',
  `content` json NOT NULL COMMENT '持久业务Context，禁止混入凭证和身份授权字段',
  `size_bytes` int NOT NULL COMMENT '序列化UTF-8大小，应用层限制',
  `revision` bigint NOT NULL DEFAULT 1 COMMENT '默认1；条件更新防覆盖',
  `updated_by_key_id` bigint NOT NULL COMMENT 'p_access_key.id，记录后端修改来源',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_session_context_1` (`session_id`),
  KEY `idx_s_session_context_1` (`account_id`, `session_id`),
  CONSTRAINT `fk_s_session_context_session_id` FOREIGN KEY (`session_id`) REFERENCES `s_session` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_s_session_context_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_session_context_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_s_session_context_session_id` CHECK (`session_id` > 0),
  CONSTRAINT `ck_s_session_context_size_bytes` CHECK (`size_bytes` >= 0),
  CONSTRAINT `ck_s_session_context_revision` CHECK (`revision` > 0),
  CONSTRAINT `ck_s_session_context_updated_by_key_id` CHECK (`updated_by_key_id` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='后端维护的Session Context';

-- 消息与运行记录 / 本轮外部操作及分段状态
CREATE TABLE IF NOT EXISTS `s_operation` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '归属账号',
  `session_id` bigint NOT NULL COMMENT '所属会话',
  `turn_id` bigint NULL COMMENT '独立ASR识别时允许为空',
  `client_request_id` varchar(64) NOT NULL COMMENT '操作幂等ID；内部操作由服务确定性生成',
  `operation_type` varchar(20) NOT NULL COMMENT 'LLM/ASR/TTS/TOOL/CONTEXT',
  `ordinal` int NOT NULL COMMENT '同类型的段号/调用序号',
  `config_resource_id` bigint NULL COMMENT 'Voice/Skill/Relay版本ID，按类型解释',
  `provider_request_id` varchar(128) NULL COMMENT '上游请求ID',
  `quota_reservation_id` bigint NULL COMMENT '官方TTS平台预占ID',
  `status` varchar(24) NOT NULL COMMENT 'QUEUED/RUNNING/SUCCEEDED/FAILED/CANCELLED/UNKNOWN',
  `playback_status` varchar(20) NULL COMMENT 'WAITING/STARTED/ENDED/FAILED/SKIPPED/STOPPED/UNKNOWN；仅TTS，其他操作为空',
  `input_char_count` bigint NULL COMMENT 'TTS计额字符数，不保存纯播报正文',
  `input_hash` binary(32) NULL COMMENT '文本或参数摘要',
  `result_summary` json NULL COMMENT '白名单状态/覆盖范围/字节数等，不放原始结果或URL查询串',
  `started_at` datetime(3) NULL COMMENT '开始时间',
  `finished_at` datetime(3) NULL COMMENT '完成时间',
  `error_code` varchar(64) NULL COMMENT '安全错误码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_operation_1` (`session_id`, `client_request_id`),
  KEY `idx_s_operation_1` (`account_id`, `session_id`, `created_at`),
  KEY `idx_s_operation_2` (`turn_id`, `operation_type`, `ordinal`),
  KEY `idx_s_operation_3` (`status`, `started_at`),
  CONSTRAINT `fk_s_operation_turn_id` FOREIGN KEY (`turn_id`) REFERENCES `s_turn` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_s_operation_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_operation_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_s_operation_session_id` CHECK (`session_id` > 0),
  CONSTRAINT `ck_s_operation_turn_id` CHECK (`turn_id` > 0),
  CONSTRAINT `ck_s_operation_operation_type` CHECK (`operation_type` IN ('LLM', 'ASR', 'TTS', 'TOOL', 'CONTEXT')),
  CONSTRAINT `ck_s_operation_ordinal` CHECK (`ordinal` >= 0),
  CONSTRAINT `ck_s_operation_config_resource_id` CHECK (`config_resource_id` > 0),
  CONSTRAINT `ck_s_operation_quota_reservation_id` CHECK (`quota_reservation_id` > 0),
  CONSTRAINT `ck_s_operation_status` CHECK (`status` IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'UNKNOWN')),
  CONSTRAINT `ck_s_operation_playback_status` CHECK (`playback_status` IN ('WAITING', 'STARTED', 'ENDED', 'FAILED', 'SKIPPED', 'STOPPED', 'UNKNOWN')),
  CONSTRAINT `ck_s_operation_input_char_count` CHECK (`input_char_count` >= 0),
  CONSTRAINT `ck_s_operation_playback_type` CHECK ((`operation_type` = 'TTS' AND `playback_status` IS NOT NULL) OR (`operation_type` <> 'TTS' AND `playback_status` IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='本轮外部操作及分段状态';

-- 会话清理 / 临时对象清理登记
CREATE TABLE IF NOT EXISTS `s_temp_object` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '归属账号',
  `session_id` bigint NOT NULL COMMENT '所属会话',
  `turn_id` bigint NULL COMMENT 'ASR预输入等可空',
  `operation_id` bigint NULL COMMENT '关联操作',
  `purpose` varchar(24) NOT NULL COMMENT 'SCREENSHOT/RECORDING/TTS_AUDIO',
  `storage_provider` varchar(32) NOT NULL COMMENT '云对象存储适配器',
  `bucket` varchar(128) NOT NULL COMMENT '桶',
  `object_key` varchar(768) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'ASCII私有对象键',
  `size_bytes` bigint NOT NULL COMMENT '字节数',
  `status` varchar(20) NOT NULL COMMENT 'UPLOADING/ACTIVE/DELETE_PENDING/DELETED',
  `expires_at` datetime(3) NOT NULL COMMENT '故障情况下最长生存期',
  `next_delete_at` datetime(3) NULL COMMENT '删除重试时间',
  `delete_attempts` int NOT NULL DEFAULT 0 COMMENT '默认0',
  `last_error_code` varchar(64) NULL COMMENT '清理错误码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_temp_object_1` (`storage_provider`, `bucket`, `object_key`),
  KEY `idx_s_temp_object_1` (`account_id`, `session_id`),
  KEY `idx_s_temp_object_2` (`status`, `expires_at`),
  KEY `idx_s_temp_object_3` (`status`, `next_delete_at`),
  CONSTRAINT `ck_s_temp_object_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_temp_object_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_s_temp_object_session_id` CHECK (`session_id` > 0),
  CONSTRAINT `ck_s_temp_object_turn_id` CHECK (`turn_id` > 0),
  CONSTRAINT `ck_s_temp_object_operation_id` CHECK (`operation_id` > 0),
  CONSTRAINT `ck_s_temp_object_purpose` CHECK (`purpose` IN ('SCREENSHOT', 'RECORDING', 'TTS_AUDIO')),
  CONSTRAINT `ck_s_temp_object_size_bytes` CHECK (`size_bytes` >= 0),
  CONSTRAINT `ck_s_temp_object_status` CHECK (`status` IN ('UPLOADING', 'ACTIVE', 'DELETE_PENDING', 'DELETED')),
  CONSTRAINT `ck_s_temp_object_delete_attempts` CHECK (`delete_attempts` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='临时对象清理登记';

-- 会话清理 / 会话删除与引用释放任务
CREATE TABLE IF NOT EXISTS `s_cleanup_job` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '归属账号',
  `session_id` bigint NOT NULL COMMENT '删除对象',
  `reason` varchar(20) NOT NULL COMMENT 'USER_DELETE/EXPIRED',
  `state` varchar(24) NOT NULL COMMENT 'PENDING/DELETING/RELEASING/DONE/FAILED',
  `cursor_id` bigint NULL COMMENT '分批删除游标',
  `stage` varchar(32) NOT NULL COMMENT '当前子表或对象清理步骤',
  `attempt_count` int NOT NULL DEFAULT 0 COMMENT '默认0',
  `next_run_at` datetime(3) NULL COMMENT '重试时间',
  `lease_owner` varchar(128) NULL COMMENT '执行者',
  `lease_expires_at` datetime(3) NULL COMMENT '租约',
  `error_code` varchar(64) NULL COMMENT '安全错误',
  `finished_at` datetime(3) NULL COMMENT '完成时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_cleanup_job_1` (`session_id`),
  KEY `idx_s_cleanup_job_1` (`state`, `next_run_at`),
  KEY `idx_s_cleanup_job_2` (`state`, `lease_expires_at`),
  CONSTRAINT `ck_s_cleanup_job_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_cleanup_job_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_s_cleanup_job_session_id` CHECK (`session_id` > 0),
  CONSTRAINT `ck_s_cleanup_job_reason` CHECK (`reason` IN ('USER_DELETE', 'EXPIRED')),
  CONSTRAINT `ck_s_cleanup_job_state` CHECK (`state` IN ('PENDING', 'DELETING', 'RELEASING', 'DONE', 'FAILED')),
  CONSTRAINT `ck_s_cleanup_job_cursor_id` CHECK (`cursor_id` > 0),
  CONSTRAINT `ck_s_cleanup_job_attempt_count` CHECK (`attempt_count` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='会话删除与引用释放任务';

-- 可靠性基础表 / 本地事务事件发件箱
CREATE TABLE IF NOT EXISTS `s_outbox` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '业务归属账号；纯系统事件使用操作管理员账号',
  `event_id` varchar(64) NOT NULL COMMENT '全局事件ID',
  `event_type` varchar(64) NOT NULL COMMENT '业务事件类型',
  `aggregate_type` varchar(32) NOT NULL COMMENT '聚合实体类型',
  `aggregate_id` varchar(64) NOT NULL COMMENT '实体ID',
  `schema_version` int NOT NULL COMMENT '消息协议版本',
  `trace_id` varchar(64) NOT NULL COMMENT '追踪ID',
  `payload` json NOT NULL COMMENT '白名单标识、状态与必要用量，不含秘密/正文/素材',
  `status` varchar(20) NOT NULL COMMENT 'PENDING/SENDING/SENT',
  `attempt_count` int NOT NULL DEFAULT 0 COMMENT '默认0',
  `next_run_at` datetime(3) NULL COMMENT '发送时间',
  `lease_owner` varchar(128) NULL COMMENT '发送者',
  `lease_expires_at` datetime(3) NULL COMMENT '租约',
  `published_at` datetime(3) NULL COMMENT '发布确认时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_outbox_1` (`event_id`),
  KEY `idx_s_outbox_1` (`status`, `next_run_at`),
  KEY `idx_s_outbox_2` (`status`, `lease_expires_at`),
  CONSTRAINT `ck_s_outbox_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_outbox_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_s_outbox_schema_version` CHECK (`schema_version` > 0),
  CONSTRAINT `ck_s_outbox_status` CHECK (`status` IN ('PENDING', 'SENDING', 'SENT')),
  CONSTRAINT `ck_s_outbox_attempt_count` CHECK (`attempt_count` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='本地事务事件发件箱';

-- 可靠性基础表 / 消费事件去重
CREATE TABLE IF NOT EXISTS `s_inbox` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '事件归属账号',
  `consumer_name` varchar(64) NOT NULL COMMENT '消费逻辑标识',
  `event_id` varchar(64) NOT NULL COMMENT '上游事件ID',
  `payload_hash` binary(32) NOT NULL COMMENT '防止同事件ID不同内容',
  `processed_at` datetime(3) NOT NULL COMMENT '本地业务事务完成时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_inbox_1` (`consumer_name`, `event_id`),
  KEY `idx_s_inbox_1` (`processed_at`),
  CONSTRAINT `ck_s_inbox_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_inbox_account_id` CHECK (`account_id` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='消费事件去重';

-- 可靠性基础表 / 持久扫描任务租约
CREATE TABLE IF NOT EXISTS `s_job_lease` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `job_key` varchar(100) NOT NULL COMMENT '清理/投递/补偿扫描任务标识',
  `lease_owner` varchar(128) NULL COMMENT '当前执行实例',
  `lease_epoch` bigint NOT NULL DEFAULT 0 COMMENT '默认0；领取代数',
  `lease_expires_at` datetime(3) NULL COMMENT '租约到期',
  `last_completed_at` datetime(3) NULL COMMENT '上次完成',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_job_lease_1` (`job_key`),
  KEY `idx_s_job_lease_1` (`lease_expires_at`),
  CONSTRAINT `ck_s_job_lease_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_job_lease_lease_epoch` CHECK (`lease_epoch` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='持久扫描任务租约';

-- 会话可靠性 / 会话HTTP API幂等结果
CREATE TABLE IF NOT EXISTS `s_api_idempotency` (
  `id` bigint NOT NULL COMMENT '主键，服务生成的正整数ID',
  `created_at` datetime(3) NOT NULL COMMENT '创建时间，UTC',
  `updated_at` datetime(3) NOT NULL COMMENT '更新时间，UTC',
  `account_id` bigint NOT NULL COMMENT '所属账号',
  `scope` varchar(64) NOT NULL COMMENT '操作、应用、Session/身份及签发来源的规范对象SHA-256小写十六进制，64字符',
  `request_id` varchar(64) NOT NULL COMMENT '后端传入幂等请求ID',
  `request_hash` binary(32) NOT NULL COMMENT '规范化业务参数SHA-256；秘密字段先做服务端keyed digest，不存正文',
  `resource_type` varchar(32) NULL COMMENT 'SESSION_GRANT/REVOCATION；按接口白名单扩展',
  `resource_id` bigint NULL COMMENT 's_session_grant.id或撤销事件s_outbox.id；不是字符串event_id',
  `status` varchar(20) NOT NULL COMMENT 'PROCESSING/SUCCEEDED/FAILED',
  `error_code` varchar(64) NULL COMMENT '安全错误',
  `expires_at` datetime(3) NOT NULL COMMENT '至少保留24小时并覆盖执行/补偿期；未完成不删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_s_api_idempotency_1` (`account_id`, `scope`, `request_id`),
  KEY `idx_s_api_idempotency_1` (`expires_at`),
  CONSTRAINT `ck_s_api_idempotency_id` CHECK (`id` > 0),
  CONSTRAINT `ck_s_api_idempotency_account_id` CHECK (`account_id` > 0),
  CONSTRAINT `ck_s_api_idempotency_resource_id` CHECK (`resource_id` > 0),
  CONSTRAINT `ck_s_api_idempotency_status` CHECK (`status` IN ('PROCESSING', 'SUCCEEDED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='会话HTTP API幂等结果';
